<div class="serie albums" itemscope itemtype="http://schema.org/Book">
    <?php if (!$this->isMobile) : ?>
        <div class="sidebar col-md-4">
            <div class="album-cover-wrapper">
                <div class="album-cover">
                    <?php foreach($this->serie->albums as $k => $album) : ?>
                        <?php if ($k < 2) : ?>
                            <a rel="lightbox[album]" href="<?php echo $this->getHelper('customUrl')->getAlbumCoverUrl($album); ?>" class="zoom">
                                <?php if ($k % 2 == 0) : ?>
                                    <?php echo $this->getHelper('displayImage')->displayAlbumCover($album, 'big', 'front', '', 'itemprop="image"'); ?>
                                <?php else : ?>
                                    <?php echo $this->getHelper('displayImage')->displayAlbumCover($album, 'big', 'behind', '', 'itemprop="image"'); ?>
                                <?php endif; ?>
                            </a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
                <?php if (isset($this->serie->albums[0])) : ?>
                    <footer>
                        <a rel="lightbox[albumfooter]" href="<?php echo $this->getHelper('customUrl')->getAlbumCoverUrl($this->serie->albums[0]); ?>" class="zoom">
                            voir en grand
                        </a>
                    </footer>
                <?php endif; ?>
            </div>
            <?php echo $this->userAccountWidget('user_dashboard'); ?>
            <div class="pub">
                <?php echo $this->partial('partials/pubs300large.phtml'); ?>
                <div id='div-gpt-ad-1350911838645-0'>
                    <script type='text/javascript'>
                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350911838645-0'); });
                    </script>
                </div>
                <div id='div-gpt-ad-1350912177560-0'>
                    <script type='text/javascript'>
                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912177560-0'); });
                    </script>
                </div>
            </div>
            <?php echo $this->partial('partials/socialContacts.phtml', array('color' => 'pink')); ?>
            <?php echo $this->partial('partials/album_award.phtml', $this); ?>
            <?php if(isset($this->concours) && count($this->concours) > 0) : ?>
                <?php foreach($this->concours as $concours) : ?>
                    <?php echo  $this->partial('partials/block300.phtml', array('data' => $concours)); ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php if(isset($this->previews) && count($this->previews) > 0) : ?>
                <?php foreach($this->previews as $preview) : ?>
                    <?php echo  $this->partial('partials/block300.phtml', array('data' => $preview)); ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php echo $this->lastConcoursBloc($this); ?>
            <?php echo $this->lastGalleryBloc($this); ?>
            <?php echo $this->lastExpoBloc($this); ?>
            <div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div>
        </div>
    <?php endif; ?>
    <div class="col-md-8">
        <div class="breadcrumb">
            <ol itemscope itemtype="http://schema.org/BreadcrumbList">
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="/">
                        <span itemprop="name">Accueil</span>
                    </a>
                    <span itemprop="position" content="1">&gt;</span>
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="<?php echo $this->url(array(), 'bedetheque'); ?>">
                        <span itemprop="name">Bédéthèque</span>
                    </a>
                    <span itemprop="position" content="2">&gt;</span>
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="<?php echo $this->url(array(), 'listserie_page'); ?>">
                        <span itemprop="name">Séries</span>
                    </a>
                    <span itemprop="position" content="3">&gt;</span>
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <span itemprop="name"><?php echo $this->serie->getNomSerie(); ?></span>
                    <span itemprop="position" content="4"></span>
                </li>
            </ol>
        </div>
        <div class="row separateur">
            <div class="col-xs-12 album-title">
                <h1 class="album-title_name"><span itemprop="name"><?php echo $this->serie->getNomSerie(); ?></span></h1>
            </div>
        </div>
        <div class="row separateur">
            <section class="col-xs-12 album-infos">
                <table class="col-xs-6">
                    <?php if (!empty($this->serie->dessinateurs)) : ?>
                    <tr>
                        <td class="label"><?php echo count($this->serie->dessinateurs) > 1 ? 'Dessinateurs' : 'Dessinateur'; ?>&nbsp;:</td>
                        <td class="info">
                             <?php foreach ($this->serie->dessinateurs as $dessinateur): ?>
                                    <h2><a href="<?php echo $this->customUrl(array('nomAuteur'=> $dessinateur->prenomAuteur. ' ' . $dessinateur->nomAuteur, 'idAuteur' => $dessinateur->idAuteur ),'auteur') ?>" itemprop="author">
                                       <?php echo $dessinateur->prenomAuteur.' '.$dessinateur->nomAuteur?></a></h2><br />
                               <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php if (!empty($this->serie->scenaristes)) : ?>
                    <tr>
                        <td class="label"><?php echo count($this->serie->scenaristes) > 1 ? 'Scénaristes' : 'Scénariste'; ?>&nbsp;:</td>
                        <td class="info">
                            <?php foreach ($this->serie->scenaristes as $scenariste): ?>
                                <h2><a href="<?php echo $this->customUrl(array('nomAuteur'=> $scenariste->prenomAuteur. ' ' . $scenariste->nomAuteur, 'idAuteur' => $scenariste->idAuteur),'auteur') ?>" itemprop="author">
                                    <?php echo $scenariste->prenomAuteur.' '.$scenariste->nomAuteur ?></a></h2><br />
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php if (!empty($this->serie->coloristes)) : ?>
                    <tr>
                        <td class="label"><?php echo count($this->serie->coloristes) > 1 ? 'Coloristes' : 'Coloriste'; ?>&nbsp;:</td>
                        <td class="info">
                            <?php foreach ($this->serie->coloristes as $coloriste): ?>
                                <h2><a href="<?php echo $this->customUrl(array('nomAuteur'=> $coloriste->prenomAuteur . ' ' . $coloriste->nomAuteur, 'idAuteur' => $coloriste->idAuteur), 'auteur') ?>" itemprop="author">
                                    <?php echo $coloriste->prenomAuteur . ' ' . $coloriste->nomAuteur ?></a></h2><br />
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td class="label">Éditions&nbsp;:</td>
                        <td class="info">
                            <?php if (!empty($this->serie->editeurs)) : ?>
                                <?php foreach ($this->serie->editeurs as $editeur) : ?>
                                    <h2>
                                        <?php $addrWebEditeur = $editeur->getAdrWebEditeur(); if (!empty($addrWebEditeur)) : ?>
                                        <a itemprop="publisher" target="_blank" href="<?php echo (strpos($editeur->getAdrWebEditeur(), 'http://') ? '' : 'http://').$editeur->getAdrWebEditeur(); ?>">
                                            <?php echo trim($editeur->getPrenomEditeur().' '.$editeur->getNomEditeur()); ?>
                                        </a>
                                    <?php else : ?>
                                        <span itemprop="publisher"><?php echo trim($editeur->getPrenomEditeur().' '.$editeur->getNomEditeur()); ?></span>
                                    <?php endif; ?>
                                    </h2><br />
                                <?php endforeach; ?>
                            <?php else : ?>
                                <span>NC</span>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php if (!empty($this->serie->collections)) : ?>
                    <tr>
                        <td class="label">Collection&nbsp;:</td>
                        <td class="info"><h2><?php echo $this->serie->collections->getNomCollection(); ?></h2><br /></td>
                    </tr>
                    <?php endif; ?>
                </table>
                <table class="col-xs-6">
                    <?php if (!empty($this->serie->motcles)) : ?>
                    <tr>
                        <td class="label">Genre&nbsp;:</td>
                        <td class="info">
                            <?php $m = array(); ?>
                            <?php foreach ($this->serie->motcles as $key => $motcle) : ?>
                                <?php $m[] = '<h2><a href="'.$this->customUrl(array('tag' => $motcle->getLibelle()), 'recherche').'" title="'.str_replace(array('"', "'"), '', strip_tags($motcle->getDefinition())).'" itemprop="genre">'.$motcle->getLibelle().'</a></h2>'; ?>
                            <?php endforeach; ?>
                            <?php echo implode(', ', $m); ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                </table>
            </section>
        </div>
        <?php echo $this->partial('partials/social_links.phtml', $this); ?>
        <div class="row">
            <section class="also-like col-xs-12">
                <h3>Tous les albums de la série <?php echo $this->serie->getNomSerie(); ?></h3>
                <ul class="row">
                    <?php foreach($this->serie->albums as $album) : ?>
                        <li class="col-xs-6 col-md-3">
                            <div class="album-wrapper">
                                <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($album, 'album'); ?>">
                                    <?php echo $this->getHelper('displayImage')->displayAlbumCover($album, 'alsolike'); ?>
                                </a>
                                <div class="title-wrapper">
                                    <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($album, 'album'); ?>">
                                        <h2><?php echo $album->getTitre(); ?></h2>
                                    </a>
                                    <?php if ($album->getTome()) : ?>
                                    <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($album, 'album'); ?>">
                                        <span>Tome # <?php echo $album->getTome(); ?></span>
                                    </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </section>
        </div>
    </div>
</div>
