      
        
<!-- CONTENU -->

<div class="leftActu">
	<h1><a href="">Le blog</a> - Toute l'actualité de la bande-dessinée</h1>
	
	<section class="actu-wrapper">
		<time datetime="2012-09-13">03 <span>sept</span></time>
		<hgroup>
			<h1><a href="">Fusion avoir-alire/bedeo</a></h1>
			<h2>Posté par Phibes - Catégorie : Actu</h2>
		</hgroup>
		
		<div class="illus_masque">
			<img src="img/temp/article-illu2.jpg" alt="" class="illus">
			<img src="img/block620_white_masque.png" alt="" class="masque">
		</div>
		
		<p>Voilà, cette fois-ci c’est fait <a href="http://www.avoir-alire.com/">http://www.avoir-alire.com/</a> a accueilli cet après-midi Bedeo.fr.<br><br>
		Aujourd’hui, le nom <strong>avoir-alire</strong> (re)prend tout son sens avec une partie <strong>À voir</strong> consacrée au <strong>cinéma</strong>, et une partie <strong>À lire</strong> consacrée à la BD et à la littérature jeunesse (le Préau).<br><br>
		La partie <strong>BD</strong> sera plus orientée « recommandations de lectures » que sur le précédent site. Elle aura aussi à cœur de continuer à traiter régulièrement de l’actualité du monde de la Bande Dessinée.<br><br>
		Le contenu de Bedeo.fr sera migré progressivement et d’ici quelques semaines tout l’historique de ce site sera de nouveau disponible.</p>
		
		<!-- Bloc de liens réseaux sociaux -->
		<div class="social-links">
			<div class="fb-like" data-href="http://www.sceneario.com" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true" data-font="arial"></div>
			
			<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120"></div>

			<script type="text/javascript">
			  window.___gcfg = {lang: 'fr'};

			  (function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
		</div>
	</section>
	
	<section class="actu-wrapper">
		<time datetime="2012-09-13">13 <span>sept</span></time>
		<hgroup>
			<h1><a href="">Fusion avoir-alire/bedeo</a></h1>
			<h2>Posté par Phibes - Catégorie : Actu</h2>
		</hgroup>
		
		<div class="illus_masque">
			<img src="img/temp/article-illu3.jpg" alt="" class="illus">
			<img src="img/block620_white_masque.png" alt="" class="masque">
		</div>
		
		<p class="accroche">Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<p>Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<p>Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<p>Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<!-- Bloc de liens réseaux sociaux -->
		<div class="social-links">
			<div class="fb-like" data-href="http://www.sceneario.com" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true" data-font="arial"></div>
			
			<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120"></div>

			<script type="text/javascript">
			  window.___gcfg = {lang: 'fr'};

			  (function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
		</div>
	</section>
	
	<section class="actu-wrapper">
		<time datetime="2012-09-13">13 <span>sept</span></time>
		<hgroup>
			<h1><a href="">Fusion avoir-alire/bedeo</a></h1>
			<h2>Posté par Phibes - Catégorie : Actu</h2>
		</hgroup>
		
		<div class="illus_masque">
			<img src="img/temp/article-illu.jpg" alt="" class="illus">
			<img src="img/block620_white_masque.png" alt="" class="masque">
		</div>
		
		<p class="accroche">Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<p>Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<p>Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<p>Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit. Lorem ipsum dolor sit amet consectuer adisciping elit.</p>
		
		<!-- Bloc de liens réseaux sociaux -->
		<div class="social-links">
			<div class="fb-like" data-href="http://www.sceneario.com" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true" data-font="arial"></div>
			
			<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120"></div>

			<script type="text/javascript">
			  window.___gcfg = {lang: 'fr'};

			  (function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
		</div>
	</section>
</div>

<div class="rightActu">
	<!-- Mon compte -->
	<section class="mon-compte">
		<h1><img src="img/user.png" alt="">Mon compte</h1>
		<ul>
			<li>Albums dans ma bédéthèque <span>0407</span></li>
			<li>Albums à acheter <span>0036</span></li>
			<li>Albums manquants à mes séries <span>0559</span></li>
		</ul>
		<a href="">Accéder à ma bédéthèque</a>
	</section>
	
	<!-- Pub 300x250 -->
	<div class="pub">
		<a href="#"><img src="img/temp/pub300x250.jpg" alt="" width="300" height="250"></a>
	</div><!-- pub -->
	
	
	<!-- Concours -->
	<section class="concours">
		<header>
			<a href="#">Tout afficher &rsaquo;</a>
			<h1>Concours</h1>
		</header>
		<figure class="center">
			<img src="img/temp/concours_illus.jpg" alt="" class="illus">
			<img src="img/block300_pink_masque.png" alt="" class="masque">
		</figure>
		<h2>Du 5 au 24 Juin, gagnez l'un des 2 premiers tomes de la série GANGS</h2>
		<a href="#" class="more">Participer &rsaquo;</a>
	</section>
	
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>
