<div class="interview col-xs-12 col-md-8">
    <div class="interview-title">
        <h2><a href="<?php echo $this->customUrl(array(),'listexpo') ?>">Expositions, salons</a></h2> -
        <h1><a href="<?php echo $this->currentUrl(); ?>"><?php echo $this->titre; ?></a></h1>
    </div>
    <section class="block white col-xs-12 rounded">
        <figure class="row">
            <img class="illus" src="<?php echo $this->imageUri; ?>" alt="exposition bande-dessinée, <?php echo $this->titre; ?>" />
        </figure>
        <hgroup>
            <h1><?php echo $this->titre ; ?></h1>
            <span><?php echo $this->expo->getDate() ; ?></span>
        </hgroup>
        <div id="texte" class="table-container table-responsive"><?php echo $this->expoHtml; ?></div>
        <?php echo $this->partial('partials/social_links.phtml', $this); ?>
    </section>
</div>
<?php echo $this->partial('partials/sidebar.phtml'); ?>