       
        
<!-- CONTENU -->

<h1 class="calendrier"><a href="">Le calendrier</a> - Les rendez-vous immanquables de la bande-dessinée</h1>

<section class="calendrier">
	<header>
		<a class="previous" href="">Mois précédent</a>
		<a class="next" href="">Mois suivant</a>
		<h1>Septembre 2012</h1>
	</header>
	
	<ul>
		<li>Lundi</li>
		<li>Mardi</li>
		<li>Mercredi</li>
		<li>Jeudi</li>
		<li>Vendredi</li>
		<li>Samedi</li>
		<li>Dimanche</li>
	</ul>
	
	<div class="clear"></div>
	
	<table cellspacing="10">
		<tbody>
			<tr>
				<td class="inactive">
					<h1>27</h1>
				</td>
				<td class="inactive">
					<h1>28</h1>
				</td>
				<td class="inactive">
					<h1>29</h1>
				</td>
				<td class="inactive">
					<h1>30</h1>
				</td>
				<td class="inactive">
					<h1>31</h1>
				</td>
				<td>
					<h1>1</h1>
					<ul>
						<li class="expo"><h2><strong>Expo :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
						
						<li class="dedi"><h2><strong>Dédi :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
						
						<li class="fest"><h2><strong>Festi :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
						
						<li class="cine"><h2><strong>Ciné :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>2</h1>
					<ul>
						<li class="sal"><h2><strong>Sal :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
			</tr>
			<tr>
				<td>
					<h1>3</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
						
						<li class="aut"><h2><strong>Aut :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>4</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>5</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>6</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>7</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>8</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>9</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
			</tr>
			<tr>
				<td>
					<h1>10</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>11</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>12</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>13</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>14</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>15</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>16</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
			</tr>
			<tr>
				<td>
					<h1>17</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>18</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>19</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>20</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>21</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>22</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>23</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
			</tr>
			<tr>
				<td>
					<h1>24</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>25</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>26</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>27</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>28</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>29</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
				<td>
					<h1>30</h1>
					<ul>
						<li class="tv"><h2><strong>TV :</strong> Franck Bonnet ...</h2>
						<span><hgroup><h1>Exposition</h1><h2>Yakari plante son tipi à Thiers</h2></hgroup>
						<p>Maison de l'Aventure Industrielle<br>
						83 avenue Joseph Claussat<br>
						63300 THIERS</p><span class="arrow"></span></span></li>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
	
	<p class="legende">Légende : 
		<span class="cinema">Cinéma</span> - 
		<span class="dedicace">Dédicace</span> - 
		<span class="exposition">Exposition</span> - 
		<span class="festival">Festival</span> - 
		<span class="salon">Salon</span> - 
		<span class="tv">TV</span> - 
		<span class="autres">Autres</span>
	</p>
</section>

<!-- Reinitialisation des float -->
<div class="clear"></div>

