<div class="staticpage newsletter col-xs-12 col-md-8">
    <h1><a href="<?php echo $this -> customUrl(array(),'nl') ?>">Newsletter</a></h1>
    <div class="clearfix">
        <div class="col-xs-12 block white bloc-newsletter">
            <div class="row">
                <h2 class="col-xs-12">Inscription</h2>
                <p class="col-xs-12">Sceneario est un site très vivant. Avec plus de 200 nouvelles fiches BDs par mois, des interviews, des préviews, des galeries de croquis, des comptes rendus d'expos / festival, des news et des concours, il est important que nous puissions vous prévenir de nos mises en lignes. Pour celà nous vous invitons à vous inscrire à notre newsletter pour ne rien manquer de l'actualité du monde de la Bande Dessinée sur Sceneario.com, c'est ICI :</p>
                <form class="col-xs-12 form" enctype="application/x-www-form-urlencoded" action="/newsletter/subscribe" method="post">
                    <div class="alert"></div>
                    <div class="checkbox col-xs-12">
                        <label for="sceneario_optin">
                            <input type="checkbox" name="sceneario_optin" id="sceneario_optin" value="1" />
                            J'accepte que vous me fassiez parvenir des emails de vos partenaires
                        </label>
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        <input class="field-text" type="text" name="sceneario_text" id="sceneario_text" value="" />
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        <input type="submit" name="sceneario_submit" id="sceneario_submit" value="M'inscrire à la newsletter" class="btn field-submit">
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xs-12 block white bloc-newsletter">
            <div class="row">
                <h2 class="col-xs-12">Désinscription</h2>
                <p class="col-xs-12">Vous avez changé d'email, vous ne lisez plus de BDs, vous venez sur Sceneario tout seul tous les jours... ou vous ne nous aimez plus... pas de soucis, pour vous désinscrire c'est ICI :</p>
                <form class="col-xs-12 form" enctype="application/x-www-form-urlencoded" action="/newsletter/unsubscribe" method="post">
                    <div class="alert"></div>
                    <div class="form-group col-xs-12 col-md-6">
                        <input class="field-text" type="text" name="sceneario_text" id="sceneario_text" value="" />
                    </div>
                    <div class="form-group col-xs-12 col-md-6">
                        <input type="submit" name="sceneario_submit" id="sceneario_submit" value="Me désinscrire de la newsletter" class="btn field-submit" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php echo $this->partial('partials/sidebar.phtml'); ?>

<script type="text/javascript">
  $(document).ready(function() {
    $('.bloc-newsletter form').submit(function(e) {
      var that = this;
      $(that).find('.alert').hide();
      $(that).find('.alert').removeClass('success');
      $(that).find('.alert').removeClass('error');
      $.post($(that).attr('action'), $(that).serialize(), function(ret) {
        var data = jQuery.parseJSON(ret);
        $(that).find('.alert').addClass(data.status == true ? 'success' : 'error');
        $(that).find('.alert').html(data.message);
        $(that).find('.alert').show();
      });
      e.preventDefault();
      return false;
    });
  });
</script>