	                
<!-- CONTENU -->

<div class="galerieWrapper">
	<div class="galerie-title">
		<h2><a href="<?php echo $this->url(array(), !empty($this->isPreview) ? 'listpreview' : 'listgalerie'); ?>"><?php echo !empty($this->isPreview) ? 'Preview' : 'Galerie' ; ?></a></h2> -
		<h1><a href="<?php echo $this->currentUrl(); ?>"><?php echo $this->titre ?></a></h1>
	</div>
	<div class="galerieSlider  <?php echo $this->previewClass ?>">
		
		<ul>
                    <?php
                    foreach($this->images as $image):
                    ?>    
                       <li><a href="<?php echo $image['big'] ?>" rel="lightbox[gal]" title=""><img <?php echo $this->norotateClass ?> src="<?php  echo $image['med'] ?>" /></a></li>
                    <?php    
                    endforeach;
                    ?>
		</ul>
		
	</div>
	
	<a href="javascript:void(0);" class="prev"></a>
	<a href="javascript:void(0);" class="next"></a>
	
	<div class="sliderPagination">
            <?php foreach($this->images as $image): ?>
                <a href="#">&nbsp;</a>
            <?php endforeach; ?>
	</div>
	
	<?php
             echo $this -> socialButtons($this->currentUrl());
        ?>
	
</div>


<!-- Reinitialisation des float -->
<div class="clear"></div>

     