<div class="header-mauve col-xs-12">
    <h1><?php echo !empty($this->isPreview) ? 'Previews' : 'Galeries' ; ?></h1><p>Aujourd'hui sur Sceneario, découvrez <span><?php echo $this->countGaleries ?></span> <?php echo !empty($this->isPreview) ? 'previews' : 'galeries' ; ?></p>
</div>
<?php echo $this->partial('partials/list_3_cols.phtml', $this); ?>
<?php echo $this->paginationControl( $this->paginator, 'Sliding', 'paginationControl-interview-type.phtml' ); ?>