<?php
/*
 * Bloc blanc de 300px de large
 *
 * Les données sont issues d'un array entré en argument 
 * de la méthode $this->partial('lien/vers/le/script/html', array de data)
 * 
 * Gère les deux blocs de couleurs blanc et rose.
 */

$blockColor = strtolower($this->data['couleur']) ;

if(!null == $this->data):
?>
<div class="<?php echo $blockColor ?>block300">
	<header>
		<a href="<?php echo $this->data['lien']['tout_afficher'] ?>" class="more">Tout afficher &rsaquo;</a>
		<h1><?php echo $this->data['rubrique'] ?></h1>
	</header>
	<figure class="center">
		<img src="<?php echo $this->data['image']?>" alt="<?php echo str_replace(array('"',"'","`"), '',$this->data['titre']) ?>" class="illus"/>
		<img src="/img/block300_<?php echo $blockColor ?>_masque.png" alt="" class="masque"/>
	</figure>
	<h2><?php echo $this->data['titre'] ?></h2>
	<?php if($blockColor !== 'pink'):  ?><p><?php echo $this->data['sous_titre'] ?></p><?php endif; ?>
	<a href="<?php echo $this->data['lien']['url'] ?>" class="more"><?php echo $this->data['lien']['type'] ?> &rsaquo;</a>
</div>
<!-- *block300 -->
<?php
endif;
?>