   <?php 
//HABILLAGE PUBLICITAIRE
 
   
if(isset($this->habillageHome) && $this->habillageHome == true): ?>
<div id="habillage-container">
	<div id="habillage">
		    	<link rel="stylesheet" href="/uploads/habillages/habillage-bedeo.css">
		        	<!--/* OpenX Javascript Tag v2.8.10 */-->

<!--/** L'image de sauvegarde de cette balise a été générée pour être utilisée sur une page 	* non-SSL. Ci cette balise doit être placée sur une page SSL, changez le 	*   'http://ads.culture-regie.com/www/delivery/...' 	* par 	*   'https://ads.culture-regie.com/www/delivery/...' 	*
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://ads.culture-regie.com/www/delivery/ajs.php':'http://ads.culture-regie.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=59");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://ads.culture-regie.com/www/delivery/ck.php?n=a93b6f43&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://ads.culture-regie.com/www/delivery/avw.php?zoneid=59&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a93b6f43' border='0' alt='' /></a></noscript>
	        		      
	</div>
</div>
               
<?php  endif;

?>