<?php

/*
 * HABILLAGE PUBLICITAIRE
 * PORTEE :
 * 2 tout le site sans la home
 * 1 tout le site
 * 0 que la home
 */

define('HABILLAGE_URL', 'http://images.sceneario.com/pubs/habillages/');

$habillageMapper = new Core_Model_Mapper_Tblhabillage();
$clause          = APPLICATION_ENV == 'testing' ?  'actifDev = ?' :  'actif = ?' ;
$habillageModels = $habillageMapper->fetchAll(2, array('clause' =>   $clause  , 'params' => IS_PUBLISHED), null);
?>
<?php if (!null == $habillageModels) : ?>
<?php foreach ($habillageModels as $habillageObj) : ?>
<?php
	// si la portée est 1, on n'execute pas
	if ($habillageObj->getPortee() !== 1) {
		if (isset($this->habillageHome)) {
			// si on est sur la home et que la portée est 2,
			// on n'execute pas la suite du script
			// et on ré-itère
			if ( $this->habillageHome == true) {
				if ($habillageObj->getPortee() == 2) {
					continue ;
				}
			}
		} else {
			// idem si on pas sur la home et que la portée est 0
			if ($habillageObj->getPortee() == 0) {
				continue ;
			}
		}
	}
?>
	<div id="habillage-container">
		<div id="habillage">
			<?php if ($habillageObj->getCss() !== '' ) : ?>
                <?php echo '<link rel="stylesheet" href="'. HABILLAGE_URL . $habillageObj->getCss() .'">'; ?>
	    	<?php endif; ?>
	    	<?php if ($habillageObj->getCouleur() !== '') : ?>
		    	<?php $couleur = $habillageObj->getCouleur(); ?>
                <?php echo '<style> body { background: '.($couleur[0] == '#' ? $couleur : '#'.$couleur).' !important; } </style>'; ?>
	    	<?php endif; ?>
	        <?php if( $habillageObj->getBanniere()) : ?>
	        	<?php echo $habillageObj->getBanniere(); ?>
	        <?php endif; ?>
		</div>
	</div>
<?php endforeach; ?>
<?php endif; ?>