<div class="header-mauve col-xs-12">
    <div class="search row">
        <form class="form-input col-xs-12 col-md-6" action="<?php echo $this->customUrl( array('tag' => '') , 'recherche') ?>" method="get">
            <input type="text" name="tag" value='<?php echo isset($this->requeteUser) && $this->userFilter != 'genres' ? $this->requeteUser : '' ?>' placeholder="Rechercher" />
            <div class="menu">
                <?php if (empty($this->userFilter) || !isset($this->searchFilter[$this->userFilter])) : ?>
                    <a href="javascript:void(0);">Tout le site</a>
                <?php else : ?>
                    <a href="javascript:void(0);"><?php echo $this->searchFilter[$this->userFilter]; ?></a>
                <?php endif; ?>
                <ul>
                    <li data-value="all">Tout le site</li>
                    <li data-value="titre_serie">Titre ou série</li>
                    <li data-value="auteurs">Les auteurs</li>
                    <li data-value="editeurs">Les éditeurs</li>
                    <li data-value="isbn">ISBN</li>
                    <li data-value="redacteurs">Les rédacteurs</li>
                </ul>
            </div>
            <input type="hidden" name="filter" value="<?php echo !empty($this->userFilter) && $this->userFilter != 'genres' ? $this->userFilter : 'all'; ?>" />
            <input type="submit" value="<?php echo $this->isMobile ? 'OK' : 'Rechercher' ; ?>" />
        </form>
        <form class="form-genre col-xs-12 col-md-6" action="<?php echo $this->customUrl( array('tag' => '') , 'recherche') ?>" method="get">
            <div class="menu">
                <?php if (empty($this->requeteUser) || !in_array($this->requeteUser, $this->genres)) : ?>
                    <a href="javascript:void(0);">Rechercher par thème</a>
                <?php else : ?>
                    <a href="javascript:void(0);"><?php echo $this->requeteUser; ?></a>
                <?php endif; ?>
                <ul>
                    <?php foreach ($this->genres as $genre) : ?>
                        <li data-value="<?php echo $genre; ?>"><?php echo $genre; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <input type="hidden" name="filter" value="genres" />
            <input type="hidden" name="tag" value="<?php echo $this->requeteUser; ?>" />
            <input type="submit" value="<?php echo $this->isMobile ? 'OK' : 'Rechercher' ; ?>" />
        </form>
    </div>
</div>