<?php
    $a = $b = $c = array();
    $c[] = '
<div class="pub">
    <!-- Home300x250 -->
    <div id="div-gpt-ad-1350912979829-0"  style="width:300px; height:250px;">
        <script type="text/javascript">
        googletag.cmd.push(function() { googletag.display(\'div-gpt-ad-1350912979829-0\'); });
        </script>
    </div>
    <div id="div-gpt-ad-1457810657334-2" style="height:250px; width:300px;">
        <script type="text/javascript">
            googletag.cmd.push(function() { googletag.display(\'div-gpt-ad-1457810657334-2\'); });
        </script>
    </div>
</div><!-- pub --> ';
foreach ($this->paginator as $key => $bloc) {
    $keyModulo = $key % 3 ;
    switch($keyModulo){
        case 0 :
            $a[] = $bloc ;
            break;
        case 1 :
            $b[] = $bloc ;
            break;
        case 2 :
            $c[] = $bloc ;
            break;
    }
}
$blocDatas = array($a,$b,$c);
?>
<?php foreach ($blocDatas as $key => $blocs) : ?>
    <div class="col-xs-12 col-md-4">
        <?php foreach ($blocs as $key => $bloc) : ?>
            <?php echo $bloc; ?>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>