<?php /*
Code pub général a mettre juste au dessus des codes pub de toute les pages :
*/ ?>
<!-- Pub300x250 -->
<div id='div-gpt-ad-1353592137472-0'>
<script type='text/javascript'>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1353592137472-0'); });
</script>
</div>

<?php /*
Code sceneario général a mettre juste au dessus des codes sceneario de toutes les pages :
*/ ?>
<!-- Sceneario300 -->
<div id='div-gpt-ad-1353592926924-0'>
<script type='text/javascript'>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1353592926924-0'); });
</script>
</div>