<div class="row">
    <div class="col-xs-12 social-links">
        <div class="fb-like" data-href="<?php echo $this->currentUrl() ?>" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true" data-font="arial"></div>
        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
        <div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120"></div>
    </div>
</div>