<!-- CONTENU -->
<div class="leftCDC">
	<h1>Coups de coeur</h1>
	
	<section class="classement hebdomadaire">
            <h1>Le classement hebdomadaire</h1>
            <ul>
                <?php foreach($this->albumWinnerSemaine as $key => $albumSemaine): 
                        $albumUrl =  $this->customUrl( array('titleSerie' => $albumSemaine['titreSerie'] , 
                                                             'titleAlbum' => $albumSemaine['titreAlbum'], 
                                                             'idAlbum'    => $albumSemaine['idAlbum'] ) , 
                                                       'album'); 
                        $coverUri =  $this->customUrl(array('isbn'   => $albumSemaine['isbn'] ,'format' => 'medium'), 'couverture') ;                            
                    ?>
                     <li>
                    <a href="<?php echo $albumUrl ?>">
                        <?php echo $this->displayImage($coverUri, $albumSemaine['titreSerie'] . ' ' . $albumSemaine['titreAlbum'], 'cover'  ) ?>      
                        <img src="/img/ruban<?php echo $key+1 ?>.png" alt="" class="ruban">
                    </a>
                    </li>
                <?php endforeach; ?>

            </ul>

            <?php  echo $this -> socialButtons($this->currentUrl()); ?>
	</section>
	
	<section class="classement an2012">
            <h1>Le classement 2012</h1>
            <ul>
                <?php foreach($this->albumWinnerAnnee as $key => $albumAnnee): 

                        $albumUrl =  $this->customUrl( array('titleSerie' => $albumAnnee['titreSerie'] , 
                                                             'titleAlbum' => $albumAnnee['titreAlbum'], 
                                                             'idAlbum'    => $albumAnnee['idAlbum'] ) , 
                                                       'album'); 
                        $coverUri =  $this->customUrl(array('isbn'   => $albumAnnee['isbn'] ,'format' => 'medium'), 'couverture') ;                            
                    ?>
                     <li>
                    <a href="<?php echo $albumUrl ?>">
                        <?php echo $this->displayImage($coverUri, $albumAnnee['titreSerie'] . ' ' . $albumAnnee['titreAlbum'], 'cover'  ) ?>      
                        <img src="/img/ruban<?php echo $key+1 ?>.png" alt="" class="ruban">
                    </a>
                    </li>
                <?php endforeach; ?>


            </ul>

              <?php  echo $this -> socialButtons($this->currentUrl()); ?>
	</section>
	
	<section class="classement equipe">
            <h1>Les coups de coeur de l'équipe</h1>

            <div class="cdc_wrapper">
                <ul>
                <?php foreach($this->albumStaff as  $k => $albumsPerMember): 
                        static $i = 0 ;
                        $i++;
                        ?>
            
                       
                        <?php
                        foreach($albumsPerMember as $key => $a):
                            if($key < 2):
                              $albumUrl =  $this->customUrl( array('titleSerie' => $a->collection . ' ' . $a->tome , 
                                                                   'titleAlbum' => $a->titre , 
                                                                   'idAlbum'    => $a->idAlbum ) , 
                                                             'album'); 
                              $coverUri =  $this->customUrl(array('isbn' => $a->isbn ,'format' => 'coupdecoeurequipe'), 'couverture') ; 
                              ?>

                          <li>
                            <a href="<?php echo $albumUrl ?>">
                                <?php echo $this->displayImage($coverUri, $a->collection . ' ' . $a->tome . ' ' . $a->titre , 'cover'  ) ?>
                                <img src="/img/coeur-coin.png" alt="" class="coeur">
                            </a>
                          </li>
                            <?php endif; ?>

                <?php endforeach ?>
                          </ul>
                <div class="clear"></div>
                
                <h2>Les coups de coeur <?php
                            $voyelles = array('a', 'o', 'i', 'u', 'e', 'y' );
                            $de = 'de ' ;
                            if(in_array(strtolower($k[0]),$voyelles) ){
                                $de = 'd\'' ;
                            }
                            
                            echo $de . $k ?></h2>
                   </div>
            
                      
                   
                   <?php 
                   #echo $i . ' ' . count($this->albumStaff) ;
                   if($i !== count($this->albumStaff)): ?>
                         <div class="cdc_wrapper">
                        <ul>
                   <?php endif; ?>
                              
                <?php endforeach; ?>


            <div class="clear"></div>
	</section>
        
</div>

<div class="rightCDC">
	<?php
	   echo $this->userAccountWidget('user_dashboard');
           echo $this->lastConcoursBloc($this);
	?>
	
	<!-- Pub 300x250 -->
	<div class="pub">
            <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Recherche300pub -->
            <div id='div-gpt-ad-1350913318651-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913318651-0'); });
                </script>
            </div>
            <!-- Recherche300interne -->
            <div id='div-gpt-ad-1350913404071-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913404071-0'); });
                </script>
            </div>
	</div><!-- pub -->
	
	<?php
	   echo $this->lastInterviewBloc($this);
           echo $this->lastGalleryBloc($this);
           echo $this->lastExpoBloc($this);
           echo $this->lastGalleryBloc($this, 'preview');
	   echo $this->registerNewsletter($this);
        ?>
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>
