<div class="coupsdecoeur col-xs-12 col-md-8">
    <h1>Coups de coeur</h1>
    <section class="classement hebdomadaire row">
        <div class="col-xs-12"><h1>Le classement hebdomadaire</h1></div>
        <div class="col-xs-12">
            <div class="cdc_wrapper">
                <ul class="row">
                  <?php foreach($this->albumWinnerSemaine as $key => $albumSemaine): ?>
                    <?php $albumUrl = $this->customUrl(array(
                                'titleSerie' => $albumSemaine['titreSerie'],
                                'titleAlbum' => $albumSemaine['titreAlbum'],
                                'idAlbum'    => $albumSemaine['idAlbum']
                            ),
                            'album'
                        );
                        $coverUri = $this->customUrl(array(
                                'isbn'   => $albumSemaine['isbn'],
                                'format' => 'medium',
                                'seo'    => $albumSemaine['titreSerie'].'-'.$albumSemaine['titreAlbum']
                            ),
                            'couverture'
                        );
                    ?>
                    <li class="col-xs-4">
                      <a href="<?php echo $albumUrl ?>">
                        <?php echo $this->displayImage($coverUri, 'bande-dessinée, '. $albumSemaine['titreSerie'] . ', ' . $albumSemaine['titreAlbum'], 'cover'  ) ?>
                        <img src="/img/ruban<?php echo $key+1 ?>.png" alt="avis bande-dessinée, meilleur bande-dessinée, <?php echo $albumSemaine['titreSerie']; ?>" class="ruban">
                      </a>
                    </li>
                  <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php  echo $this -> socialButtons($this->currentUrl()); ?>
    </section>
    <section class="classement an2012 row">
        <div class="col-xs-12"><h1>Le classement <?php echo date('Y'); ?></h1></div>
        <div class="col-xs-12">
            <div class="cdc_wrapper">
                <ul class="row">
                  <?php foreach($this->albumWinnerAnnee as $key => $albumAnnee): ?>
                    <?php $albumUrl = $this->customUrl(array(
                                'titleSerie' => $albumAnnee['titreSerie'],
                                'titleAlbum' => $albumAnnee['titreAlbum'],
                                'idAlbum'    => $albumAnnee['idAlbum'],
                            ),
                            'album'
                        );
                        $coverUri = $this->customUrl(array(
                                'isbn'   => $albumAnnee['isbn'],
                                'format' => 'medium',
                                'seo'    => $albumAnnee['titreSerie'].'-'.$albumAnnee['titreAlbum']
                            ),
                            'couverture'
                        );
                    ?>

                    <li class="col-xs-4">
                      <a href="<?php echo $albumUrl ?>">
                        <?php echo $this->displayImage($coverUri, 'bande-dessinée, '. $albumAnnee['titreSerie'] . ', ' . $albumAnnee['titreAlbum'], 'cover'  ) ?>
                        <img src="/img/ruban<?php echo $key+1 ?>.png" alt="avis bande-dessinée, meilleur bande-dessinée, <?php echo $albumAnnee['titreSerie']; ?>" class="ruban">
                      </a>
                    </li>
                  <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php  echo $this -> socialButtons($this->currentUrl()); ?>
    </section>
    <section class="classement equipe row">
        <div class="col-xs-12"><h1>Les coups de coeur de l'équipe</h1></div>
        <div class="col-xs-12">
            <div class="cdc_wrapper">
                <div class="row">
                    <?php foreach($this->albumStaff as  $k => $albumsPerMember): ?>
                    <div class="col-xs-12 col-md-6">
                      <ul class="row">
                        <?php foreach($albumsPerMember as $key => $a) : ?>
                          <?php if($key < 2) : ?>
                            <li class="col-xs-6">
                              <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($a); ?>">
                                <?php echo $this->getHelper('displayImage')->displayAlbumCover($a, 'coupdecoeurequipe', 'cover'); ?>
                                <img src="/img/coeur-coin.png" alt="avis bande-dessinée, meilleur bande-dessinée, <?php echo $a->collection; ?>" class="coeur">
                              </a>
                            </li>
                          <?php endif; ?>
                        <?php endforeach ?>
                      </ul>
                      <h2>Les coups de coeur
                        <?php $voyelles = array('a', 'o', 'i', 'u', 'e', 'y' ); $de = 'de '; ?>
                        <?php if (in_array(strtolower($k[0]),$voyelles)) $de = 'd\''; ?>
                        <?php echo $de . $k ?>
                      </h2>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </section>
</div>

<?php echo $this->partial('partials/sidebar.phtml'); ?>