<div id="bedetheque">
    <header class="header-mauve col-xs-12">
        <p>Aujourd'hui, la bédéthèque de Sceneario c'est : <span><?php echo $this->nbCritiques ?></span> chroniques sur <span><?php echo $this->nbAlbums ?></span> albums par <span><?php echo $this->nbAuteurs ?></span> auteurs</p>
    </header>

    <div class="col-xs-12 col-md-4">
        <a class="btn col-xs-12" href="<?php echo $this->url(array(), 'listserie_page'); ?>">Les séries</a>
    </div>
    <div class="col-xs-12 col-md-4">
        <a class="btn col-xs-12" href="<?php echo $this->url(array(), 'listalbum_page'); ?>">Les albums</a>
    </div>
    <div class="col-xs-12 col-md-4">
        <a class="btn col-xs-12" href="<?php echo $this->url(array(), 'listauteur_page'); ?>">Les auteurs</a>
    </div>
        
    <section class="itemBedetheque col-xs-12">
        <h1><a href="<?php echo $this->customUrl(array('tag' => 'nouveautes'), 'listalbum') ?>">Nouveautés</a></h1>
        <div class="albums-slider" data-mcs-theme="dark">
            <?php echo $this->partial('partials/listingAlbum.phtml', array('albums' => $this->newAlbums)); ?>
        </div>
    </section>

    <section class="itemBedetheque col-xs-12">
        <h1>Derniers ajouts</h1>
        <div class="albums-slider" data-mcs-theme="dark">
            <?php echo $this->partial('partials/listingAlbum.phtml', array('albums' => $this->recentAlbums)); ?>
        </div>
    </section>

    <section class="itemBedetheque col-xs-12">
        <h1><a href="<?php echo $this->customUrl(array(), 'coupdecoeur') ?>">Coup de coeur</a></h1>
        <div class="albums-slider" data-mcs-theme="dark">
            <?php echo $this->partial('partials/listingAlbum.phtml', array('albums' => $this->coupsDeCoeurAlbums)); ?>
        </div>
    </section>

    <section class="itemBedetheque col-xs-12">
        <h1>Les plus vues</h1>
        <div class="albums-slider" data-mcs-theme="dark">
            <?php echo $this->partial('partials/listingAlbum.phtml', array('albums' => $this->mostViewedAlbums)); ?>
        </div>
    </section>
</div>