<div class="header-mauve col-xs-12" id="bedetheque">
    <?php if ($this->type == 'bedetheque') : ?>
        <form name="formFilter" id="formFilter" method="get" action="">
            <p>
                <strong><?php echo $this->bdtekTile; ?></strong>
                <span><?php echo $this->formatNumber(count($this->userBedetheque)); ?></span> albums
                <select name="listType" onchange="document.location.href='?'.$addUrl.'listby=\'+this.value+\'\'" >
                    <optgroup label="Options d'affichage">
                        <option value="all" ' . (($listBy == 'all') ? 'SELECTED' : '' ). ' >Montrer la totalité</option>
                        <option value="list_my_album" ' . (($listBy == 'list_my_album') ? 'SELECTED' : '') . '>dans ma bédéthèque</option>
                        <option value="list_album_to_buy" ' . (($listBy == 'list_album_to_buy') ? 'SELECTED' : '') . '> à acheter</option>
                    </optgroup>
                </select>
            </p>
        </form>
    <?php elseif ($this->type == 'nouveautes') : ?>
        <form name="formFilter" id="formFilter" method="get" action="" class="row">
        <?php if ($this->isMobile) : ?>
            <div class="col-xs-6 text-left"><h1>Nouveautés</h1></div>
            <div class="col-xs-6 text-right"><p><span><?php echo $this->formatNumber($this->countOfAlbums); ?></span></p></div>
            <div class="col-xs-4"><p><?php echo $this->dateSelecteur; ?></p></div>
            <div class="col-xs-8"><p><?php echo $this->editeurSelecteur; ?></p><input id="formFilterBt" type="submit" value="ok" /></div>
        <?php else : ?>
            <div class="col-xs-12">
                <h1>Nouveautés</h1>
                <p><span><?php echo $this->formatNumber($this->countOfAlbums); ?></span> nouveautés</p>
                <p>en <?php echo $this->dateSelecteur; ?></p><p>chez <?php echo $this->editeurSelecteur; ?></p>
                <input id="formFilterBt" type="submit" value="ok" />
            </div>
        <?php endif; ?>
        </form>
    <?php elseif ($this->type == 'recommandes') : ?>
        <h1>Recommandés</h1> <p>par Sceneario.com</p>
    <?php else : ?>
        <form id="formFilter" method="get" action="" class="row">
        <?php if ($this->isMobile) : ?>
            <div class="col-xs-6 text-left"><h1>À paraître</h1></div>
            <div class="col-xs-6 text-right"><p><span><?php echo $this->formatNumber(count($this->albumDuMoisAP)); ?></span></p></div>
            <div class="col-xs-4"><p><?php echo $this->dateSelecteur; ?></p></div>
            <div class="col-xs-8"><p><?php echo $this->editeurSelecteur; ?></p><input id="formFilterBt" type="submit" value="ok" /></div>
        <?php else : ?>
            <div class="col-xs-12">
                <h1>À paraître</h1>
                <p><span><?php echo $this->formatNumber(count($this->albumDuMoisAP)); ?></span> albums à paraître</p>
                <p>en <?php echo $this->dateSelecteur; ?><p><p>chez <?php echo $this->editeurSelecteur; ?></p>
                <input id="formFilterBt" type="submit" value="ok" />
                </p>
            </div>
        <?php endif; ?>
        </form>
    <?php endif; ?>
</div>
<?php echo $this->partial('partials/album_list.phtml', $this); ?>

<?php echo $this->partial('partials/sidebar.phtml'); ?>