
        
<!-- CONTENU -->

<header class="header-mauve"  id="bedetheque">
 
         	<?php echo $this->textHeader ?>

</header>

<div class="leftRecherche">
	<header >
           
            <p class="left">
            Résultats <?php echo $this -> pageRequested > 1 
                                 ? $this->resultsPerPage * ($this -> pageRequested-1) 
                                 : 1 ?> 
                à <?php echo ($this->countResults < $this->resultsPerPage) 
                             ?  $this->countResults 
                             :  ((($this->resultsPerPage * $this -> pageRequested) < $this->countResults) 
                                                                                   ? $this->resultsPerPage * $this -> pageRequested
                                                                                   : $this->countResults ) ;

                ?> sur <?php echo $this->countResults ?></p>
             
            <p class="right">Afficher 
                <script>
                function createUrl(count){
                    var currentUrl = window.location.href;
                    var url ;
                    var resultPerPage = 'results='+count;

                    if(currentUrl.indexOf('results=') != -1){
                        var nb = currentUrl.indexOf('results=') ;
                        currentUrl = currentUrl.substring(0, nb-1);
                    }
                    
                    if(currentUrl.indexOf('?') == -1){
                        url = currentUrl + '?' + resultPerPage ;
                    }else{
                        url = currentUrl + '&' + resultPerPage ;
                    }
                    
                    self.location.href = url ;
                }
                </script>
                    <select name="" onchange=" createUrl(this.value) " >
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 10 )echo "SELECTED" ?> value="10">10</option>
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 20 )echo "SELECTED" ?> value="20">20</option>
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 30 )echo "SELECTED" ?> value="30">30</option>
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 50 )echo "SELECTED" ?> value="50">50</option>
                    </select> 
            résultats par page</p>
       
	</header>
<?php if (count($this->paginator)): ?>
    <?php foreach ($this->paginator as $key => $hit): ?>
        <div class="item clearfix" id="id-<?php echo $hit->idAlbum ?>">
            <?php if(Zend_Registry::isRegistered('currentUserID') && $this->bedetheque && !isset($_GET['user'])): ?>
                <div style="position:absolute;z-index:1000;right:10px;top:0px;"><a style="display:block;padding:10px;" href="javascript:void(0);" onclick="javascript:deleteAlbumFromBdtech(<?php echo $hit->idAlbum ?>);">×</a></div>
            <?php endif;?>
            <?php if($hit->idAlbum != '_ALBUM_A_PARAITRE_'): ?>
                <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($hit); ?>" class="item-link clearfix">
                <?php echo $this->getHelper('displayImage')->displayAlbumCover($hit, 'small', 'cover'); ?>
            <?php endif ;?>
            <div class="search-content">
                <hgroup>
                    <h2 class="titreSerie"><?php echo $hit->titreSerie ?></h2>
                    <h2><?php echo $hit->titreAlbum ?></h2>
                </hgroup>

                <p>
                <?php  echo $hit->auteurs ?>

                <?php if($hit->editeur != ''):?>
                    <br />Editions <?php echo $hit->editeur  ?>
                <?php endif ?>
                </p>
                <?php if($hit->genres != ''): ?>
                    <p><?php echo $hit->genres ?></p>
                <?php endif; ?>
            </div>
            <?php if($hit->idAlbum != '_ALBUM_A_PARAITRE_'): ?>
                </a>
            <?php endif ;?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
       
<div class="separateur"></div>
 
<?php


echo $this->paginationControl( $this->paginator,
                               'Sliding',
                               'paginationControl-interview-type.phtml' ); ?>
	
</div>

<div class="rightRecherche">
        <!-- user widget -->
        <?php  
           echo $this->userAccountWidget('user_dashboard');
           echo $this->lastConcoursBloc($this);
        ?>

	<!-- Pub 300x250 -->
	<div class="pub">
            <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Recherche300pub -->
            <div id='div-gpt-ad-1350913318651-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913318651-0'); });
                </script>
            </div>
            <!-- Recherche300interne -->
            <div id='div-gpt-ad-1350913404071-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913404071-0'); });
                </script>
            </div>
	</div><!-- pub -->
	
	<?php
        echo $this->lastInterviewBloc($this);
	echo $this->lastGalleryBloc($this);
	echo $this->lastExpoBloc($this);
	echo $this->lastGalleryBloc($this, 'preview');
	echo $this->registerNewsletter($this);
        ?>
	
         
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" 
             data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>

    
