
<!-- CONTENU -->

<div class="leftActu">
	<h1><a href="<?php echo $this->customUrl(array(), 'accueil'); ?>">Sceneario.com</a> - Page non trouvée</h1>
	
	<section class="actu-wrapper">
		<hgroup>
                	<h1>La page que vous cherchez n'existe pas</h1>
			<h2></h2>
		</hgroup>
		<div class="illus_masque">
		  <img src="/img/temp/imgv6.jpg" alt="" class="illus">
		  <img src="/img/block620_white_masque.png" alt="" class="masque">
		</div>
		<div class="actuContent">
		  
		  <p><img src="/img/temp/v6-img1.gif"/></p>
		  
		  <p><strong>En 12 ans</strong>, Sceneario s’est imposé comme l’une des références de <strong>la bande-dessinée sur internet.</strong> Vous êtes <strong>des milliers</strong> à venir chaque jours vivre votre passion pour le neuvième art en ligne et découvrir toujours plus d’albums et d’auteurs fantastiques.</p>
		  <p><strong>En 12 ans</strong>, nos millions d’internautes nous ont poussé à en faire toujours plus et toujours mieux. <strong>Aujourd’hui Sceneario évolue</strong> et change de peau, sa sixième. Nous espérons que cette nouvelle mouture, plus légère, plus performante, plus belle et plus ergonomique vous satisfera autant que les précédentes en leur temps.</p>
		  
		  <p><img src="/img/temp/v6-img2.gif"/></p>
		  
		  <img src="/img/temp/v6-img3.jpg" style="float:right; margin-left:20px;margin-right:30px;"/>
		  <p style="color:#a22c6d;"><strong>La recherche au coeur de Sceneario</strong></p>
		  <p>Outil central du site, solicité des milliers de fois par jours, le moteur de recherche de la V6 est plus rapide et nettement plus puissant. Et en plus d’être meilleur, il est omniprésent et ne vous quittera jamais.<br/>Accédez-y à tout moment, où que vous soyez.</p>

		  <div class="clear"></div>
		  
		  <img src="/img/temp/v6-img4.jpg" style="float:left; margin-right:20px; margin-left:30px;"/>
		  <p style="margin-top:70px;color:#a22c6d;"><strong>Pour le plaisir des yeux</strong></p>
		  <p>Nos 18 585 fiches albums, complétement revue, sont plus belle et plus claire. Profitant de la pleine largeur de votre navigateur, nous avons désormais de l’espace pour vous afficher vos albums préférés comme ils le méritent.</p>
		  
		  <div class="clear"></div>
		  
		  <img src="/img/temp/v6-img5.jpg" style="float:right; margin-left:20px; margin-right:30px;"/>
		  <p style="margin-top:30px;color:#a22c6d;"><strong>Socialement connécté</strong></p>
		  <p>Vous pouvez désormais partager tout ce qui vous plait sur Sceneario. Informez vos amis, faites leur découvrir des bd, des auteurs, des interviews inédites directement sur votre mur Facebook, Twitter ou Google+</p>
		  
		  <div class="clear"></div>
		  
		  <img src="/img/temp/v6-img6.jpg" style="float:left; margin-right:20px;margin-bottom:20px;"/>
		  <p style="margin-top:100px;color:#a22c6d;"><strong>Morderne et compatible</strong></p>
		  <p>Profitant des dernières normes de développement web, cette sixième version de Sceneario est plus compatible que jamais. Surfez sur vos ordinateurs, tablettes et smartphone sans limitations.</p>
		  
		  <div class="clear"></div>
		</div>	 
	</section>
	
	
</div>

<div class="rightActu">
	<!-- Pub 300x250 -->
	<div class="pub">
              <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Album300 -->
            <div id='div-gpt-ad-1350911838645-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350911838645-0'); });
                </script>
            </div>
            <!-- Album300interne -->
            <div id='div-gpt-ad-1350912177560-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912177560-0'); });
                </script>
            </div>
	</div><!-- pub -->

	<?php echo $this->partial('partials/socialContacts.phtml')?>
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>
