<div class="auteur">
    <?php if (!$this->isMobile) : ?>
        <div class="sidebar col-md-4">
            <?php echo $this->partial('partials/album_award.phtml', $this); ?>
            <div class="pub">
                <?php echo $this->partial('partials/pubs300large.phtml'); ?>
                <div id='div-gpt-ad-1350912243655-0'>
                    <script type='text/javascript'>googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912243655-0'); });</script>
                </div>
                <div id='div-gpt-ad-1350912679192-0'>
                    <script type='text/javascript'>googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912679192-0'); });</script>
                </div>
            </div>
            <?php echo $this->partial ('partials/socialContacts.phtml', array('color' => 'pink')); ?>
            <div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div>
        </div>
    <?php endif; ?>
    <div class="col-xd-12 col-md-8">
        <div class="breadcrumb">
            <ol itemscope itemtype="http://schema.org/BreadcrumbList">
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="/">
                        <span itemprop="name">Accueil</span>
                    </a>
                    <span itemprop="position" content="1">&gt;</span>
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="<?php echo $this->url(array(), 'bedetheque'); ?>">
                        <span itemprop="name">Bédéthèque</span>
                    </a>
                    <span itemprop="position" content="2">&gt;</span>
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a itemprop="item" href="<?php echo $this->url(array(), 'listauteur_page'); ?>">
                        <span itemprop="name">Auteurs</span>
                    </a>
                    <span itemprop="position" content="3">&gt;</span>
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <span itemprop="name"><?php echo $this->nomAuteur; ?></span>
                    <span itemprop="position" content="4"></span>
                </li>
            </ol>
        </div>
        <div class="row separateur">
            <div class="col-xs-12 presentation">
                <h1><?php echo $this->nomAuteur ?></h1>
                <h2><?php echo $this->jobsAuteur ?></h2>
            </div>
        </div>
        <?php if(isset($this->bio) && $this->bio != ''): ?>
            <section class="biographie row">
                <div class="col-xs-12">
                    <h3>Biographie</h3>
                    <div class="bioWrapper"><p><?php echo $this->bio ?></p></div>
                </div>
            </section>
        <?php endif ?>
        <?php echo $this->partial('partials/social_links.phtml', $this); ?>
        <section class="also-like row">
            <div class="col-xs-12">
                <h3>Les séries de <?php echo $this->nomAuteur ?> chroniqués par Sceneario.com&nbsp;:</h3>
                <ul class="row">
                    <?php foreach ($this->albumsAuteur as $keyAlbum => $album) : ?>
                        <li class="col-xs-6 col-md-3">
                            <div class="album-wrapper">
                                <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($album); ?>">
                                    <?php echo $this->getHelper('displayImage')->displayAlbumCover($album, 'alsolike') ; ?>
                                </a>
                                <div class="title-wrapper">
                                    <h2><a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($album); ?>">
                                        <?php echo $album->collection; ?>
                                    </a></h2>
                                    <?php if( $album->tomes >  0 ): ?>
                                        <span><a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($album); ?>">
                                            (<?php echo $album->tomes ?> tome<?php echo $album->tomes >  1 ? 's' : '';  ?>)
                                        </a></span>
                                    <?php endif;?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach;?>
                </ul>
                <a href="<?php echo $this->customUrl(array('tag'=> $this->nomAuteur), 'recherche') ?>" class="button_large">Voir plus de série de <?php echo $this->nomAuteur ?></a>
            </div>
        </section>
        <?php foreach (array_chunk($this->blocDatas, 2) as $row) : ?>
            <div class="row">
                <?php foreach ($row as $bloc) : ?>
                    <div class="col-xs-12 col-md-6"><?php echo $bloc; ?></div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>