  
<!-- CONTENU -->
<?php $equipe = array(
      'Aub' => array(
        'name' => 'Aubert Bonneau',
        'city' => 'Vittel (Vosges), France',
        'mail' => 'webmaster@sceneario.com',
        'passion' => 'Ma femme, mes enfants, la BD, le VTT.',
        'type' => 'Policier / Thriller / SF',
        'role' => 'Créateur et président de Sceneario.com / Responsable communication / Rédacteur',
        'prefs' => 'Incontestablement Peter Pan, Aquablue, UW1 et 2, Le Tueur, Blacksad, Sanctuaire, Zombies...',
        'links' => array('Facebook' => 'https://www.facebook.com/Sceneario.com')
      ),
      'FredGri' => array(
        'name' => '',
        'mail' => 'fredgri@free.fr',
        'city' => 'Dijon, France',
        'passion' => 'Dessin, BD, Cinéma, mais avant tout ma puce :-)',
        'type' => 'Strip, Aventure, intimisme, “comics”, jeunesse, etc.',
        'prefs' => 'A la recherche de Peter Pan”, “Starstruck”, “Little Nemo”, “Watchmen”, “Pogo”, “Kililana Song”, “Terry & the pirates”, les “Mickey” de Gottfredson...',
        'role' => 'Rédacteur',
        'links' => array('Portfolio' => 'http://fredgri.daportfolio.com/', 'Blog' => 'http://fredgrigri.blogspot.fr/', 'Facebook' => 'http://facebook.com/Fredgri')
      ),
      'Berthold' => array(
        'name' => '',
        'mail' => 'bertholdbd@gmail.com',
        'city' => 'Espelette, France',
        'passion' => 'dessin, cinema, lecture...',
        'type' => 'thriller, aventures; polar, SF...',
        'prefs' => 'Corto Malese, Les scorpions du désert, Fort Wheeling, Blueberry, Les Tuniques Bleues, Gaston, Johan & Pirlouit, Jerry Spring, Blacksad, Le pouvoir des innocents, Batman, The Watchmen,...',
        'role' => 'Rédacteur',
        'links' => array('Facebook' => 'http://www.facebook.com/david.bertold', 'Blog' => 'http://lebertoldbd.over-blog.com/')
      ),
      'fef' => array(
        'name' => '',
        'mail' => '',
        'city' => 'secret',
        'passion' => 'bd et musique',
        'type' => 'humour, fantastique, science-fiction, comics',
        'prefs' => 'oulah, ça dépend des jours et de l\'humeur mais principalement tout gotlib, asterix, courtney crumrin, canardo, travis & carmen mc callum, avengers, requiem, ...',
        'role' => 'photographe et reportage divers',
        'links' => array()
      ),
      'Sbuoro' => array(
        'name' => '',
        'mail'=> 'sbuoro@hotmail.com',
        'city' => 'à quelques km de Carcassonne, France</p>',
        'passion' => 'BD, voyages, philatélie...',
        'type' => 'Récits de voyages, témoignages historiques...',
        'prefs' => 'Trop pour en faire la liste ! Du franco-belge, et pourquoi pas du manga.',
        'role' => 'Rédacteur',
        'links' => array(),
      ),
      'Phibes' => array(
        'name' => '',
        'mail'=> 'philippe.bes1@orange.fr',
        'city' => 'Carcassonne, France</p>',
        'passion' => 'la BD, le VTT, le chocolat…',
        'type' => 'Thriller, policier, anticipation, aventure…',
        'prefs' => 'un paquet dont Blake et Mortimer, Les Pieds Nickelés, Comanche, Blueberry, Buck Danny, Tintin, Astérix…',
        'role' => 'Rédacteur',
        'links' => array(),
      ),
      'Olivier' => array(
        'name' => 'Olivier Bequet',
        'mail' => 'olivier@sceneario.com',
        'city' => 'Le Havre, France',
        'passion' => 'Lire, chiner dans les foires à tout pour alimenter quelques collections et puis le boulot… un peu',
        'type' => 'De la bande dessinée bien sur et des romans avec les grands maitres de la science fiction comme Asimov, Van Vogt ou Farmer, de la fantasy avec Feist et Hobb, les Techno thrillers de Clancy, Di Mercurio ou Robinson, les thriller ésotériques de Delafosse, Giacometti, Graham, Sansom, l’aventure avec Higgins, Ludlum ou Cussler et puis aussi Tolkien, Lovecraft, …',
        'prefs' => 'du Franco-Belge essentiellement, je suis très éclectique au niveau de mes lectures avec un faible pour Riff Reb’s, Edith, Vatine, Kokor, Vastra, Jacamon ou Cromwell, à vous de trouver leur point commun.',
        'role' => 'Rédacteur, Intervieweur et pourvoyeur du plateau de fromage à Angoulême',
        'links' => array()
      ),
      'PEK' => array(
        'name' => 'Paul-Etienne Kauffmann',
        'mail' => 'pauletiennekauffmann@hotmail.fr',
        'city' => 'Rouen / Paris, France',
        'passion' => 'BD, Disney, Détection de métaux, Numismatique, Chiner',
        'type' => '',
        'prefs' => 'Spécialiste en BDs Disney et en journaux BD (Mickey / Spirou / Tintin / A suivre ...) j\'affectionne tout particulièrement le Franco-Belge (XIII / Largo Winch / Aria / Tuniques bleues ...) ce qui ne m\'empêche pas d\'adorer certaines séries Manga (Naruto / Black Joke / Code Breaker / Les gouttes de Dieu / Soil / ...) ou certains comics (Wolverine / Tout Dillon et Le Punisher). Enfin j\'adore par dessus tout le travail d\'Auclair et sa splendide série Simon du Fleuve.',
        'role' => 'Rédacteur et étudiant (Ce qui est parfois difficilement compatible ...)',
        'links' => array()
      ),
      'Eric' => array(
        'name' => '',
        'mail' => 'eric@sceneario.com',
        'city' => 'Paris, France',
        'passion' => 'bd et pas B&D, mon iPhone, la natation, les yeux bleus, le whisky, le vin, le rugby, Joe satriani, Shakaponk, Triggerfinger, stuck in the sound, Apocalyptica, ...',
        'type' => 'polar ( Indrisason, Feray, Lehane,...) SF ( Herbert, Weber, Campbell, ...)',
        'prefs' => 'Aquablue, universal war one, le IIIeme testament, lanfeust de Troy, Ghost in the Shell, Appleseed, Gunnm, Spirou, Herobear and the kid, Jim Lee, Michael Turner',
        'role' => 'intermitant du rédactionnel',
        'links' => array('Facebook' => 'http://facebook.com/emariani', 'Twitter' => 'http://twitter.com/ericsceneario')
      ),
      'Placido' => array(
        'name' => '',
        'mail'=> 'pvirey@gmail.com',
        'city' => 'Dijon, France</p>',
        'passion' => 'Hocher la tête à des concerts Rock, fureter dans les bacs des disquaires, glisser avec des rollers aux pieds, me nourrir de fromage et de vin.',
        'type' => 'BD franco-belges.',
        'prefs' => 'Corto Maltese, Adèle Blanc-Sec, Isaac Le Pirate, Hiram Lowatt & Placido, Les Idées Noires. Les BD de chez Futuropolis et de L\'Asssociation. Les collections Poisson Pilote et Air Libre.',
        'role' => 'Rédacteur',
        'links' => array('Facebook' => 'http://facebook.com/pierre.virey'),
      ),
      'boukrou' => array(
        'name' => '',
        'mail'=> '',
        'city' => 'Paris, France',
        'passion' => 'Informatique, High-Tech, Moto, Mangas, Skimboard',
        'type' => 'Énormément mangas, mais pourquoi pas quelques franco-belges et/ou comics de temps en temps.',
        'prefs' => 'Dragon Ball, Gunnm, Bleach, Naruto, Bakuman, Death Note, Code Geass, Samurai Champloo, Steins;Gate, NHK ni Youkoso, Full Metal Alchemist, Claymore ... mais aussi Largo Winch, Blake et Mortimer, ou encore, Wolverine, The Walking Dead !',
        'role' => 'Développeur et rédacteur',
        'links' => array(),
      ),
      'MaTT' => array(
        'name' => '',
        'mail'=> 'matteo@hotmail.fr',
        'city' => 'Paris, France</p>',
        'passion' => 'Bd, Musique, Tennis, Photographie',
        'type' => 'Plutôt axé sur les parutions Delcourt (Collection Série B, Terres de légende, Shampooing...) et sur les comics de l\'univers Marvel, mais toujours intéressé par de nouvelles découvertes tous éditeurs confondus !',
        'prefs' => 'Blacksad, La Licorne, Blast, Garulfo, De Capes Et De Crocs, Le Combat Ordinaire, MertownVille, Sillage, Travis, Carmen Mc Callum, Notes, Donjon, Spirou, Marzi, Soda...',
        'role' => 'Chroniqueur / Intervieweur',
        'links' => array('Facebook' => 'http://www.facebook.com/matthieu.brun.5'),
      ),
      'Arneau' => array(
        'name' => '',
        'mail'=> 'arneau.m@gmail.com',
        'city' => 'Nantes, France</p>',
        'passion' => 'le cinéma et le barbecue',
        'type' => 'polar, sf, littérature générale',
        'prefs' => 'Larcenet, Dorison, Peeters, Bouzard, Brunschwig, Pedrosa, Brüno, Meyer, Vives, Lauffray, Bendis, Brubaker, Loeb/Sale, Hellboy, The Goon, Spirou, Quai d\'orsay, Ghost Money,Ibicus, CArmen Mac callum, Y the last man, DMZ, Wolverine...',
        'role' => 'rédacteur, intervieweur',
        'links' => array('Facebook' => 'http://www.facebook.com/arnaud.micheau'),
      ),
      'Beuleu' => array(
        'name' => '',
        'mail'=> 'beuleu@sceneario.com',
        'city' => 'Le Havre, France</p>',
        'passion' => 'ouhla ... trop de trucs !',
        'type' => 'heroic fantasy, SF, policier ... et magazines de couture/broderie :D',
        'prefs' => 'Le Vent dans les Saules, Algernon Woodcock, Troll de Troy, Magasin général, La Jungle en folie, les Tuniques Bleues, Usagi Yojimbo et tant d\'autres ...',
        'role' => 'rédactrice et correctrice à l\'occasion',
        'links' => array('Facebook' => 'http://facebook.com/BeuleuSceneario'),
      ),
      'Tito' => array(
        'name' => '',
        'mail'=> '',
        'city' => 'St Didier sur Chalaronne, France</p>',
        'passion' => 'regarder grandir mes enfants et sceneario.com, guitare, procrastiner et jouer (musique, jdg, mmo, jdp, Kübb...) !',
        'type' => '',
        'prefs' => 'celles que j\'ai le temps de lire',
        'role' => 'mouche du coche',
        'links' => array('Twitter' => 'http://www.twitter.com/Random95'),
      ),
      'Melville' => array(
        'name' => '',
        'mail'=> '',
        'city' => '',
        'passion' => 'Cinéma',
        'type' => 'Romans et BDs, Revues',
        'prefs' => 'Balade au Bout du Monde (cycle 1), Corto Maltese, Rork et Capricorne',
        'role' => 'Rédacteur',
        'links' => array(),
      ),
      'Clémence' => array(
        'name' => '',
        'mail'=> 'clemence@sceneario.com',
        'city' => 'Paris, France',
        'passion' => 'Jeux vidéos, films d\'animation japonais, séries en tous genres...',
        'type' => 'Littérature anglo-saxonne, science-fiction, heroic-fantasy',
        'prefs' => 'Fées et Tendres Automates, Peter Pan, Universal War One, Sambre et bien d\'autres',
        'role' => 'Rédactrice',
        'links' => array(),
      ),
  );
?>

<div class="leftActu staticpage equipe">
  <h1><a href="<?php echo $this->customUrl(array(), 'equipe') ?>">Équipe</a> - Tous les membres Sceneario.com</h1>

  <div class="presentation clearfix">
    <p>
      <a href="http://www.sceneario.com">Sceneario.com</a> est un site généraliste traitant de Bande Dessinée, spécialisé dans la critique de BD, de Comics et de Mangas. Avec plus de 20 000 fiches BDs résumant et analysant les parutions internationales, 550 interviews, 450 préviews, 270 comptes rendus d’expositions / salons, 180 galeries de croquis, des concours, Sceneario.com est un site de référence et un incontournable du monde de la Bande Dessinée.
    </p>
    <div class="first"><img src="/images/equipe/equipe.jpg" alt="Fondation équipe - 2004" />AG Sceneario.com · 2004</div>
    <div><img src="/images/equipe/equipe_dos.jpg" alt="Équipe - Angoulême 2010" />L'équipe à Angoulême · 2011</div>
  </div>

  <?php $i = 0; ?>
  <?php foreach ($equipe as $membre => $infos) : ?>
  <div class="redacteur <?php print $i % 2 == 0 ? 'even' : 'odd'; ?>">
    <header>
      <div class="picture <?php print $i % 2 == 0 ? 'revert' : ''; ?>">
        <img src="<?php print file_exists('images/equipe/'.$membre.'.jpg') ? '/images/equipe/'.$membre.'.jpg' : '/images/equipe/user.jpg'; ?>" />
      </div>
      <h2 class="name"><?php print $membre; ?></h2>
      <span class="full-name"><?php print $infos['name']; ?></span>
      <span class="email"><a href="mailto:<?php print $infos['mail']; ?>"><?php print $infos['mail']; ?></a></span>
    </header>
    <div class="full-description">
      <?php if(!empty($infos['city'])) : ?><p><span>Ville et pays de résidence :</span> <?php print $infos['city']; ?></p><?php endif; ?>
      <?php if(!empty($infos['passion'])) : ?><p><span>Passion(s) :</span> <?php print $infos['passion']; ?></p><?php endif; ?>
      <?php if(!empty($infos['type'])) : ?><p><span>Type de lecture :</span> <?php print $infos['type']; ?></p><?php endif; ?>
      <?php if(!empty($infos['prefs'])) : ?><p><span>BD préférée(s) :</span> <?php print $infos['prefs']; ?></p><?php endif; ?>
      <?php if(!empty($infos['role'])) : ?><p><span>Fonction sur le site :</span> <?php print $infos['role']; ?></p><?php endif; ?>
      <?php if(!empty($infos['links'])) : ?><p><span>Liens :</span>
        <?php foreach($infos['links'] as $w => &$link) : ?><?php $link = '<a href="'.$link.'">'.$w.'</a>'; ?><?php endforeach; ?>
        <?php print implode($infos['links'], ', '); ?>
      </p><?php endif; ?>
      <p class="avis">
        <a href="/recherche?tag=<?php print $membre; ?>&filter=Les+rédacteurs">
          <strong><?php print Core_Model_Mapper_Tblcritique::getCritiquesNumberByRedacteur($membre); ?></strong> avis</a>
        </p>
    </div>
  </div>
  <?php $i++; ?>
  <?php endforeach; ?>

</div>

<div class="rightActu">
  <?php 
     echo $this->userAccountWidget('user_dashboard');
     echo $this->lastConcoursBloc($this);
  ?>
	<!-- Pub 300x250 -->
	<div class="pub">
            <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Interview300 -->
            <div id='div-gpt-ad-1350913175803-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913175803-0'); });
                </script>
            </div>
            <!-- Interview300interne -->
            <div id='div-gpt-ad-1350913216188-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913216188-0'); });
                </script>
            </div>
	</div><!-- pub -->
	
	<?php 
           echo $this->lastInterviewBloc($this);  
	   echo $this->lastGalleryBloc($this);
	   echo $this->lastExpoBloc($this);
	   echo $this->lastGalleryBloc($this, 'preview');
	   echo $this->registerNewsletter($this);
	?>
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>
