   
<!-- CONTENU -->

<div class="leftActu staticpage legalmentions">
	<section class="actu-wrapper">
	  <div class="actuContent">
	    <h2>Mentions Légale</h2>
	    <p>
	      <a href="<?php echo $this -> customUrl(array(), 'accueil') ?>">Sceneario.com</a> est régie par l’association loi 1901 nommée Sceneario.com déclarée le 21 septembre 2004 et enregistrée le 2 novembre 2004 à la Sous-Préfecture des Vosges de Neufchateau sous le numéro de dossier 2458
	      <br />
	      Journal Officiel 136° année N°48 (page 5377) et Journal Officiel 137° année N°1 (Rectification en page 105)
	    </p>
	    <p>
	      Président : Aubert BONNEAU<br />
	      Trésorier : Ronan MONTAUBAN<br />
	      Secrétaire : Sandryne BONNEAU<br />
	    </p>
	    <p>
	      Siege Social au domicile du Président<br />
	      Aubert BONNEAU<br />
	      Sceneario<br />
	      90 rue de l’Avrimont<br />
	      88 800 Remoncourt
	    </p>
	    <p>
	      Adresse Postale :<br />
	      Sceneario<br />
	      BP 23<br />
	      88801 Vittel Cedex<br />
	      <br />
	      Tel : 06-71-92-28-8trois
	    </p>

	    <h2>Droits d’auteurs</h2>
	    <p>
	      Toutes les images, dessins et planches figurant sur Sceneario.com sont la propriété des Editeurs et de leurs Auteurs.<br />
	      <br />
	      Leur utilisation doit faire l'objet d'une demande d'autorisation à leurs propriétaires.<br />
	      <br />
	      Si des visuels sont publiés sur Sceneario.com et que leurs propriétaires ne le souhaite pas ou plus, nous les retirerons dès que la demande nous sera parvenue.
	    </p>
 
	    <h2>Création de liens</h2>
	    <p>
	      Le site Sceneario.com autorise la création de liens hypertext pointant vers son contenu, aux conditions ci-dessous:<br />
	      <ul>
		<li>Pas d'utilisation en lien profond (Les pages de Sceneario.com ne doivent pas être reprises à l'intérieure d'un autre site mais donner lieu à l’ouverture d’une fenêtre propre)</li>
		<li>Une mention de la source dans l’intitulé du lien pointant vers ledit contenu visé doit être présente.</li>
	      </ul>
	    </p>

	    <h2>Protection des données personnelles</h2>
	    <p>
	      Aucune information personnelle n’est collectée à votre insu<br />
	      Aucune information personnelle n’est cédée ou vendue à des tiers.<br />
	      Aucune information personnelle n’a été blessée ou maltraitée durant la conception de ce site Internet.<br />
	      Aucun bénéfice mercantile n’est généré à votre insu.<br />
	      Le recours à un cookie a uniquement pour but l’accès pragmatique et direct à vos usages de lecture et de consultation du site, ainsi que le paramétrage automatique de vos informations et préférences. Vous pouvez le désactiver.<br />
	      Nous pouvons recueillir des données statistiques (nombre de pages vues, de consultations, modes de consultations) afin de mieux identifier pages consultées et d'en déduire les centres d’intérêts des internautes de Sceneario, afin d'en améliorer le contenu et de l'adapter aux visiteurs. Ces données demeurent bien entendu totalement anonymes.<br />
	      Les informations fournies via les formulaires en ligne font l’objet d’un traitement informatisé par nos soins.<br />
	      <br />
	      Conformément à la loi « Informatique et Libertés », vous pouvez nous demander un droit d’accès aux informations vous concernant, par email en utilisant le formulaire de contact ou en écrivant à Sceneario.com BP 23. 88801 Vittel Cedex<br />
	      Sceneario.com est déclaré à la CNIL sous le n° (En cours)
	    </p>

	  </div>
	</section>
</div>

<div class="rightActu">
  <?php 
     echo $this->userAccountWidget('user_dashboard');
     echo $this->lastConcoursBloc($this);
  ?>
	<!-- Pub 300x250 -->
	<div class="pub">
            <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Interview300 -->
            <div id='div-gpt-ad-1350913175803-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913175803-0'); });
                </script>
            </div>
            <!-- Interview300interne -->
            <div id='div-gpt-ad-1350913216188-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913216188-0'); });
                </script>
            </div>
	</div><!-- pub -->
	
	<?php 
           echo $this->lastInterviewBloc($this);  
	   echo $this->lastGalleryBloc($this);
	   echo $this->lastExpoBloc($this);
	   echo $this->lastGalleryBloc($this, 'preview');
	   echo $this->registerNewsletter($this);
	?>
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>
