<div class="staticpage contact col-xs-12 col-md-8">
    <h1><a href="<?php echo $this->url(); ?>">Contact</a></h1>
    <div class="block white col-xs-12">
        <div class="row">
            <div class="col-xs-12">
                <h2>Vous avez des questions, des remarques, des suggestions&nbsp;?</h2>
                <p>N'hésitez pas à nous contacter&nbsp;!</p>
                <p>Vous souhaitez annoncer sur Sceneario.com&nbsp;? Notre <a href="http://regie.sceneario.com" target="_blank">régie</a> répond à vos besoins.</p>
            </div>
            <div class="col-xs-12 col-md-10 col-md-offset-1">
                <?php echo $this->partial('_forms/contact.phtml', 'Core', array('form' => $this->form)); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->partial('partials/sidebar.phtml'); ?>