
        
        <div id="content-container">
	        <div id="content">
		        
	        
        
        
<!-- CONTENU -->

<div class="leftActu">
	<h1><a href="">Le blog</a> - Toute l'actualité de la bande-dessinée</h1>
	
	<section class="actu-wrapper">
		<time datetime="2012-09-13">03 <span>sept</span></time>
		<hgroup>
			<h1><a href="">Fusion avoir-alire/bedeo</a></h1>
			<h2>Posté par Phibes - Catégorie : Actu</h2>
		</hgroup>
		
		<div class="illus_masque">
			<img src="img/temp/article-illu2.jpg" alt="" class="illus">
			<img src="img/block620_white_masque.png" alt="" class="masque">
		</div>
		
		<p class="accroche">A l’occasion de la parution du très attendu Colère Rouge, le 18ème tome de Largo Winch, les Editions Dupuis proposent une expérience unique et participative à tous les fans de la célèbre bande dessinée de Philippe Francq et Jean Van Hamme. Dupuis a souhaité profiter de cet événement pour remercier les fans de Largo de leur fidélité, en leur proposant une expérience exceptionnelle.</p>

		<p>My Major Company, leader européen du financement participatif permet à tous les créateurs de projets culturels et innovants d’obtenir le soutien du grand public. Les internautes ont la possibilité sur www.mymajorcompany.com de soutenir la création au sens large et dans tous types de domaines : l’art et le patrimoine, la BD, le cinéma, les jeux, le livre, la musique, la photographie, le spectacle vivant, le sport etc.<br><br>
		
		Depuis plus de 20 ans, les aventures du célèbre milliardaire aventurier le plus populaire de la bande dessinée franco-belge sont suivies par une immense communauté. Ce nouvel opus est donc très attendu et devrait satisfaire les jeunes et moins jeunes férus de Largo. Jean Van Hamme campe d’ailleurs la trame de ce tome dans les arcanes du trafic d’armes et du terrorisme international, pour mieux surprendre son public.<br><br>
		
		« Toute l’équipe de Largo Winch voulait offrir aux fans de la BD une expérience inédite et en profondeur de l’univers de Largo. Notre plateforme participative est un outil rêvé pour cela : les internautes peuvent accéder à des contenus et des rencontres uniques et exceptionnels. L’expérience participative révolutionne le rapport du public au contenu. » commente Victor Lugger, Directeur Général Finance My Major Company.<br><br>
		
		Chaque contribution donnera droit en avant-première à une lecture en streaming du nouvel opus ! Les contributions plus généreuses permettront d’accéder par exemple à des contenus exceptionnels, comme un « tiré à part » issu de Colère Rouge, (tirage supplémentaire et limité d’un extrait de planche), le documentaire Largo en DVD et un exemplaire dédicacé de la version Grand Format ou Luxe du tome 18, et même une rencontre exclusive de Jean Van Hamme, Philippe Francq et leurs éditeurs.<br><br>
		
		Ce projet étant limité dans le temps il est possible d’y participer entre le 6 septembre et le 18 octobre 2012. Sortie prévue de Colère Rouge le 19 octobre.<br><br>
		
		Pour retrouver toutes les informations et bénéficier de toutes ces contreparties, rendez-vous ici.<br><br>
		
		<em>« Depuis deux ans nous avons associé les fans de BD à des projets de jeunes talents sur My Major Company. Les internautes ont immédiatement répondu à l’appel. Aujourd’hui c ‘est une nouvelle étape dans notre utilisation de la plateforme participative : permettre aux fans d’une série mythique d’aller plus loin dans leur passion. Nous pensons qu’internet doit rapprocher les communautés de fans et les créateurs qui donnent vie à leurs héros. Pour nous, cette interaction ludique répond au besoin croissant de conversation entre la série et ses lecteurs, notamment les lecteurs historiques dont la fidélité mérite toute notre attention.» ajoute Pierre Bellet, directeur marketing des Editions Dupuis.</em></p>
		
		<!-- Bloc de liens réseaux sociaux -->
		<div class="social-links">
			<div class="fb-like" data-href="http://www.sceneario.com" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true" data-font="arial"></div>
			
			<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120"></div>

			<script type="text/javascript">
			  window.___gcfg = {lang: 'fr'};

			  (function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
		</div>
	</section>
	
	<section class="comments">
		<h1>2 commentaires sur "Largo Winch sur My Major Company"</h1>
		<ul>
			<li>
				<strong>blanchet ludivine :</strong>
				<p>Bonjour,<br><br>
					Je vous contacte simplement pour savoir combien de numéros restent à venir ? (en sachant qu'on en est au numéro 22!!!!!)<br><br>
					Est-ce indéfini ? ou y a t-il par exemple 30 figurines et puis ça s'arrête ?<br>
					Mon buraliste n'a pas su me répondre ....
				</p>
			</li>
			<li>
				<strong>blanchet ludivine :</strong>
				<p>Bonjour,<br><br>
					Je vous contacte simplement pour savoir combien de numéros restent à venir ? (en sachant qu'on en est au numéro 22!!!!!)<br><br>
					Est-ce indéfini ? ou y a t-il par exemple 30 figurines et puis ça s'arrête ?<br>
					Mon buraliste n'a pas su me répondre ....
				</p>
			</li>
		</ul>
	</section>
	
	<section class="write-comment">
		<h1>Laisser un commentaire</h1>
		<form action="" method="">
			<label>Nom *</label>
			<input type="text" name="nom" value="">
			
			<label>Mail *</label>
			<input type="text" name="mail" value="">
			
			<textarea name="commentaire"></textarea>
			
			<input type="submit" name="post-commentaire" value="Poster le commentaire >">
		</form>
	</section>
</div>

<div class="rightActu">
	<!-- Mon compte -->
	<section class="mon-compte">
		<h1><img src="img/user.png" alt="">Mon compte</h1>
		<ul>
			<li>Albums dans ma bédéthèque <span>0407</span></li>
			<li>Albums à acheter <span>0036</span></li>
			<li>Albums manquants à mes séries <span>0559</span></li>
		</ul>
		<a href="">Accéder à ma bédéthèque</a>
	</section>
	
	<!-- Pub 300x250 -->
	<div class="pub">
		<a href="#"><img src="img/temp/pub300x250.jpg" alt="" width="300" height="250"></a>
	</div><!-- pub -->
	
	
	<!-- Concours -->
	<section class="concours">
		<header>
			<a href="#">Tout afficher &rsaquo;</a>
			<h1>Concours</h1>
		</header>
		<figure class="center">
			<img src="img/temp/concours_illus.jpg" alt="" class="illus">
			<img src="img/block300_pink_masque.png" alt="" class="masque">
		</figure>
		<h2>Du 5 au 24 Juin, gagnez l'un des 2 premiers tomes de la série GANGS</h2>
		<a href="#" class="more">Participer &rsaquo;</a>
	</section>
	
	<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>

        
		<div class="clear"></div>
	</div><!-- content -->
</div><!-- content-container -->
