<div class="concours col-xs-12">
    <h3>&Agrave; gagner en ce moment sur Sceneario&nbsp;!</h3>
    <div class="block white col-xs-12 rounded concours-current">
        <figure class="row">
            <?php $filename = file_exists(ROOT_PATH.PUBLIC_DIR.'/images/concours/'.$this->concoursEnCours->getNomConcours().'.jpg') ? '/images/concours/'.$this->concoursEnCours->getNomConcours().'.jpg' : '/img/temp/scev6-tempconcours.jpg'; ?>
            <img src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>" class="illus" />
        </figure>
        <h1 class="hidden-xs"><?php echo $this->concoursEnCours->getLibelleConcours() ?></h1>
        <div class="concours-description row separateur">
            <div class="col-xs-12 col-md-9">
                <h2>Du <?php echo $this->dateFormat($this->concoursEnCours->getDateDebut(), 'day_month_year_with_slash').' au '.$this->dateFormat($this->concoursEnCours->getDateFin() , 'day_month_year_with_slash'); ?></h2>
                <h3><?php echo strip_tags($this->concoursEnCours->getEntete()) ?></h3>
            </div>
            <?php if (!empty($this->album_related)) : ?>
                <div class="col-xs-12 col-md-3">
                    <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($this->album_related); ?>" class="big_button">Voir la fiche BD</a>
                </div>
            <?php endif; ?>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-8">
                 <?php if ($this->concoursTermine == false) : ?>
                    <form class="row" id="form_questions" action="<?php echo $this->customUrl(array( 'nomConcours' => $this->concoursEnCours->getLibelleConcours(), 'idConcours' => $this->concoursEnCours->getNomConcours()), 'concoursstep2') ?>" method="post">
                        <?php foreach ($this->concoursQuestion as $key => $question) : ?>
                            <?php $codeQuestion = 1; ?>
                            <div class="form-group col-xs-12">
                                <label for="q1">Question 1 : <strong><?php echo $question->getQuestion() ?> ?</strong></label>
                                <input type="text" class="concours_reponses form-control" name="concours_reponses[reponse_q_1]" id="q1" value="" placeholder="Réponse :" required="required" />
                            </div>
                        <?php endforeach; ?>
                        <div class="form-group col-xs-12">
                            <label for="qsubsid">Question subsidiaire : <strong>Sur toute la durée de ce concours, combien y aura-t-il de réponses ?</strong></label>
                            <input class="concours_reponses form-control" type="number" name="concours_reponses[reponse_q_subsidiaire]" id="qsubsid" value="" placeholder="Réponse:" required="required" pattern="[0-9]+" />
                        </div>
                        <input type="hidden" name="concours_process[token]" value="<?php echo uniqid(true) ?>" />
                        <input type="hidden" name="concours_process[step1]" value="1" />
                        <div class="col-xs-12"><div class="alert error"></div></div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3"><input type="submit" class="big_button" value="Valider mes réponses" /></div>
                    </form>
                <?php else : ?>
                    <?php if (date('Y-m-d') < $this->concoursEnCours->getDateFin() && empty($this->concoursQuestion)) : ?>
                        <p class="no-questions">Il n'y a pas de question aujourd'hui, revenez demain !<br /></p>
                    <?php else : ?>
                        <?php if ($this->concoursEnCours->getResultats() != '') : ?>
                            <?php $resultat = trim(($this->concoursEnCours->getResultats() ), '<br>'); ?>
                            <?php $resultat = trim(($this->concoursEnCours->getResultats() )); ?>
                            <h2>Voici les résultats du concours Sceneario.com :</h2>
                            <p><?php echo strip_tags(trim(str_replace('<br>', ' / ', $resultat ), '/  /')); ?></p>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <p class="reglement">
                    <a target="_blank" href="<?php echo $this->customUrl(array( 'nomConcours' => $this->concoursEnCours->getLibelleConcours(), 'idConcours' => $this->concoursEnCours->getNomConcours()), 'concoursreglement') ?>">Voir le réglement du concours</a>
                </p>
            </div>
            <div class="col-xs-12 col-md-4">
                <?php if (!empty($this->album_related)) : ?>
                <div class="block pink clearfix">
                    <header>
                        <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($this->album_related); ?>" class="more pull-right">Voir la fiche BD &rsaquo;</a>
                        <a href="/galerie"><h3>Fiche BD</h3></a>
                    </header>
                    <figure class="row">
                        <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($this->album_related); ?>">
                            <img class="illus" src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>">
                        </a>
                    </figure>
                    <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($this->album_related); ?>">
                        <h2><?php echo $this->album_related->getCollection(); ?></h2>
                        <p><?php echo ($this->album_related->getTome() != '' ? 'Tome ' . $this->album_related->getTome().' - ' : '').$this->album_related->getTitre(); ?></p>
                    </a>
                    <a href="<?php echo $this->getHelper('customUrl')->getAlbumUrl($this->album_related); ?>" class="btn pull-right">Voir la fiche BD &rsaquo;</a>
                </div>
                <?php endif; ?>
                <div class="pub">
                    <div id="div-gpt-ad-1350912979829-0"  style="width:300px; height:250px;">
                        <script type="text/javascript">googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912979829-0'); });</script>
                    </div>
                    <div id='div-gpt-ad-1457810657334-3'>
                        <script type='text/javascript'>
                            googletag.cmd.push(function() { googletag.display('div-gpt-ad-1457810657334-3'); });
                        </script>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>