<!-- CONTENU -->
<h1 class="concours">&Agrave; gagner en ce moment sur Sceneario !</h1>

<div class="whiteblock940">
   
        <figure class="center">
		<?php
                $filename =  '/images/concours/' . $this->concoursEnCours->getNomConcours() . '.jpg' ;
                if(!file_exists(ROOT_PATH . PUBLIC_DIR .  $filename)): 
                     $filename = "/img/temp/scev6-tempconcours.jpg";      
                endif; ?>
            <img src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>" class="illus" />
		<figcaption><h1><?php echo $this->concoursEnCours->getLibelleConcours() ?></h1></figcaption>
	</figure>
    
	<hgroup>
            <h2>Du <?php echo $this->dateFormat($this->concoursEnCours->getDateDebut() , 'day_month_year_with_slash') 
                          . ' au ' .  $this->dateFormat($this->concoursEnCours->getDateFin() , 'day_month_year_with_slash' ) ?></h2>
            <h3><?php echo strip_tags($this->concoursEnCours->getEntete()) ?></h3>
	</hgroup>
    <?php if (!empty($this->album_related)) : ?>
        <a href="<?php echo $this->customUrl(array('titleSerie' => $this->album_related->getCollection().($this->album_related->getTome() != '' ? ' ' . $this->album_related->getTome() : ''),
                    'titleAlbum' => $this->album_related->getTitre(),
                    'idAlbum' => $this->album_related->getIdAlbum()),
                    'album' ); ?>" class="fiche_album">Voir la fiche BD ></a>
    <?php endif; ?>
	<!-- Reinitialisation des float -->
	<div class="clear"></div>
	
	<div class="separateur"></div>
<div class="left-column">
	<form id="form_questions" action="<?php echo $this->customUrl(array( 'nomConcours' => $this->concoursEnCours->getLibelleConcours() , 
                                                         'idConcours'  => $this->concoursEnCours->getNomConcours()), 'concoursstep2') ?>" method="post">
           
        
         <?php 
         if($this->concoursTermine == false):   
            foreach($this->concoursQuestion as $key => $question): 
                    $codeQuestion = 1 ;//$question->getNumQuestion() ;
                ?>
		<label for="q1">Question 1 : <strong><?php echo $question->getQuestion() ?> ?</strong></label>
		<input type="text" class="concours_reponses" name="concours_reponses[reponse_q_1]" id="q1" value="" placeholder="Réponse :" required="required">
		
		
            <?php endForeach; ?>
                <label for="qsubsid">Question subsidiaire : <strong>Sur toute la durée de ce concours, combien y aura-t-il de réponses ?</strong></label>
		<input class="concours_reponses" type="text" name="concours_reponses[reponse_q_subsidiaire]" id="qsubsid" value="" placeholder="Réponse:" required="required" pattern="[0-9]+">
                <input type="hidden" name="concours_process[token]" value="<?php echo uniqid(true) ?>">
                <input type="hidden" name="concours_process[step1]" value="1">
                <a href="javascript:void(0);"   id="submitconcourstep1" class="submit">Valider mes réponses <img src="/img/concours-fleche.png" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>" /></a>
                <div id="messageValidation"></div>
        </form>
	<?php
        else:
            if (date('Y-m-d') < $this->concoursEnCours->getDateFin() && empty($this->concoursQuestion)) : ?>
                <p class="no-questions">Il n'y a pas de question aujourd'hui, revenez demain !<br />
                </p>
            <?php else :
            if($this->concoursEnCours->getResultats() != ''): 
                $resultat = trim(($this->concoursEnCours->getResultats() ), '<br>') ;
                $resultat = trim(($this->concoursEnCours->getResultats() )) ;
                ?>
                <h2>Voici les résultats du concours Sceneario.com :</h2>
                <p><?php echo strip_tags(trim(str_replace('<br>', ' / ', $resultat ), '/  /')); ?></p><?php
                
            endif;
            endif;
        endif;
        ?>
        <div class="clear"></div>
        <p class="reglement"><a target="_blank" href="
            <?php echo $this->customUrl(array( 'nomConcours' => $this->concoursEnCours->getLibelleConcours() , 
                                               'idConcours'  => $this->concoursEnCours->getNomConcours()), 
                                        'concoursreglement') ?>">Voir le réglement du concours</a></p>
</div>
<div class="right-column">
    <?php if (!empty($this->album_related)) : ?>
    <div class="pinkblock300">
        <header>
            <a href="<?php echo $this->customUrl(array('titleSerie' => $this->album_related->getCollection().($this->album_related->getTome() != '' ? ' ' . $this->album_related->getTome() : ''),
                    'titleAlbum' => $this->album_related->getTitre(),
                    'idAlbum' => $this->album_related->getIdAlbum()),
                    'album' ); ?>" class="more">Voir la fiche BD ></a>

            <a href="/galerie"><h3>Fiche BD</h3></a>
        </header>
        <figure class="center">
            <a href="<?php echo $this->customUrl(array('titleSerie' => $this->album_related->getCollection().($this->album_related->getTome() != '' ? ' ' . $this->album_related->getTome() : ''),
                    'titleAlbum' => $this->album_related->getTitre(),
                    'idAlbum' => $this->album_related->getIdAlbum()),
                    'album' ); ?>">
                <img src="<?php echo $this->customUrl( array('isbn'=> $this->album_related->getIsbn(), 'format'=> 'big') , 'couverture' ) ?>" alt="<?php echo str_replace(array('"',"'","`"), '', $this->album_related->getCollection().' '.($this->album_related->getTome() != '' ? 'Tome ' . $this->album_related->getTome() : '').' - '.$this->album_related->getTitre()); ?>">
            </a>
        </figure>
        <a href="<?php echo $this->customUrl(array('titleSerie' => $this->album_related->getCollection().($this->album_related->getTome() != '' ? ' ' . $this->album_related->getTome() : ''),
                    'titleAlbum' => $this->album_related->getTitre(),
                    'idAlbum' => $this->album_related->getIdAlbum()),
                    'album' ); ?>">
            <h2>
                <?php echo $this->album_related->getCollection(); ?><br />
                <?php echo ($this->album_related->getTome() != '' ? 'Tome ' . $this->album_related->getTome().' - ' : '').$this->album_related->getTitre(); ?>
            </h2>
        </a>
        <a href="<?php echo $this->customUrl(array('titleSerie' => $this->album_related->getCollection().($this->album_related->getTome() != '' ? ' ' . $this->album_related->getTome() : ''),
                    'titleAlbum' => $this->album_related->getTitre(),
                    'idAlbum' => $this->album_related->getIdAlbum()),
                    'album' ); ?>" class="more">Voir la fiche BD ›</a>
    </div>
    <?php endif; ?>

    <div class="pub">
        <div id="div-gpt-ad-1350912979829-0"  style="width:300px; height:250px;">
            <script type="text/javascript">
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912979829-0'); });
            </script>
        </div>
    </div>
</div>
	<!-- Reinitialisation des float -->
<div class="clear"></div>
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>