<div class="concours col-xs-12">
    <h3>&Agrave; gagner en ce moment sur Sceneario&nbsp;!</h3>
    <div class="block white col-xs-12 rounded concours-current">
        <figure class="row">
            <?php $filename = file_exists(ROOT_PATH.PUBLIC_DIR.'/images/concours/'.$this->concoursEnCours->getNomConcours().'.jpg') ? '/images/concours/'.$this->concoursEnCours->getNomConcours().'.jpg' : '/img/temp/scev6-tempconcours.jpg'; ?>
            <img src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>" class="illus" />
        </figure>
        <h1 class="hidden-xs"><?php echo $this->concoursEnCours->getLibelleConcours() ?></h1>
        <div class="concours-description row">
            <div class="col-xs-12 col-md-9">
                <h2>Du <?php echo $this->dateFormat($this->concoursEnCours->getDateDebut(), 'day_month_year_with_slash').' au '.$this->dateFormat($this->concoursEnCours->getDateFin() , 'day_month_year_with_slash'); ?></h2>
                <h3><?php echo strip_tags($this->concoursEnCours->getEntete()) ?></h3>
            </div>
            <div class="col-xs-12 col-md-3">
                <a href="<?php echo $this->customUrl(array( 'nomConcours' => $this->concoursEnCours->getLibelleConcours(), 'idConcours' => $this->concoursEnCours->getNomConcours()), 'concoursstep1') ?>" class="big_button">Participez</a>
            </div>
        </div>
        <div class="row">
            <div class="reglement-concours col-xs-12 col-md-8">
        	    <p><?php echo $this->concoursEnCours->getReglement() ?></p>
	       </div>
        </div>
    </div>
</div>