<!-- CONTENU -->
<h1 class="concours">&Agrave; gagner en ce moment sur Sceneario !</h1>

<div class="whiteblock940">
 
        <figure class="center">
           <?php
                $filename =  '/images/concours/' . $this->concoursEnCours->getNomConcours() . '.jpg' ;
                if(!file_exists(ROOT_PATH . PUBLIC_DIR .  $filename)): 
                     $filename = "/img/temp/scev6-tempconcours.jpg";      
                endif; ?>
            <img src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>" class="illus">
                ?>
		<figcaption><h1><?php echo $this->concoursEnCours->getLibelleConcours() ?></h1></figcaption>
	</figure>
     
	<hgroup>
            <h2>Du <?php echo $this->dateFormat($this->concoursEnCours->getDateDebut() , 'day_month_year_with_slash') 
                          . ' au ' .  $this->dateFormat($this->concoursEnCours->getDateFin() , 'day_month_year_with_slash' ) ?></h2>
            <h3><?php echo strip_tags($this->concoursEnCours->getEntete()) ?></h3>
	</hgroup>
    <?php if (!empty($this->album_related)) : ?>
        <a href="<?php echo $this->customUrl(array('titleSerie' => $this->album_related->getCollection().($this->album_related->getTome() != '' ? ' ' . $this->album_related->getTome() : ''),
                    'titleAlbum' => $this->album_related->getTitre(),
                    'idAlbum' => $this->album_related->getIdAlbum()),
                    'album' ); ?>" class="fiche_album">Voir la fiche BD ></a>
    <?php endif; ?>
	<!-- Reinitialisation des float -->
	<div class="clear"></div>
	
	<div class="separateur"></div>
	<div class="left-column">
		<p class="confirm"><?php echo $this->message ?></p>
<div class="clear"></div>

	    <p class="reglement"><a target="_blank" href="<?php echo $this->customUrl(array( 'nomConcours' => $this->concoursEnCours->getLibelleConcours() , 
                                                         'idConcours'  => $this->concoursEnCours->getNomConcours()), 'concoursreglement') ?>">Voir le réglement du concours</a></p>
	</div>
	<div class="right-column">
	    <div class="pub">
	        <div id="div-gpt-ad-1350912979829-0"  style="width:300px; height:250px;">
	            <script type="text/javascript">
	                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912979829-0'); });
	            </script>
	        </div>
	    </div>
	</div>
	<!-- Reinitialisation des float -->
<div class="clear"></div>
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>