<!-- CONTENU -->
<h1 class="concours">&Agrave; gagner en ce moment sur Sceneario !</h1>

<div class="whiteblock940">
 
        <figure class="center">
           <?php
                $filename =  '/images/concours/' . $this->concoursEnCours->getNomConcours() . '.jpg' ;
                if(!file_exists(ROOT_PATH . PUBLIC_DIR .  $filename)): 
                     $filename = "/img/temp/scev6-tempconcours.jpg";      
                endif; ?>
            <img src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $this->concoursEnCours->getLibelleConcours()) ?>" class="illus">
                ?>
		<figcaption><h1><?php echo $this->concoursEnCours->getLibelleConcours() ?></h1></figcaption>
	</figure> 
     
        
	<hgroup>
            <h2>Du <?php echo $this->dateFormat($this->concoursEnCours->getDateDebut() , 'day_month_year_with_slash') 
                          . ' au ' .  $this->dateFormat($this->concoursEnCours->getDateFin() , 'day_month_year_with_slash' ) ?></h2>
            <h3><?php echo strip_tags($this->concoursEnCours->getEntete()) ?></h3>
	</hgroup>
        <?php echo $this->linkAlbum ?>
	
	<!-- Reinitialisation des float -->
	<div class="clear"></div>
	
	<div class="separateur"></div>
	
        <form>
            <p>
                <?php echo $this->concoursEnCours->getReglement() ?>
            </p>
	</form>	
	
	
	
	<!-- Reinitialisation des float -->
<div class="clear"></div>
	
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>