<div class="concours concours-list col-xs-12">
    <?php if($this->concoursEnCours != null): ?>
        <h3>&Agrave; gagner en ce moment sur Sceneario&nbsp;!</h3>
    <?php endif; ?>
    <?php foreach ($this->concoursEnCours as $concourEnCours) : ?>
        <?php echo $this->partial('partials/concoursEnCours.phtml', array('data' => $concourEnCours)); ?>
    <?php endforeach; ?>
    <h3>Les concours précédents</h3>
    <div class="row">
        <?php foreach ($this->concoursPrecedentsOrdered as $key => $concoursPrecedents) : ?>
            <div class="col-xs-12 col-md-4 rounded">
                <?php foreach ($concoursPrecedents as $k => $concPrec) : ?>
                    <?php if ($key == 2 && $k == 1) : ?>
                        <div class="pub">
                            <div id="div-gpt-ad-1350912979829-0" style="width:300px; height:250px;">
                                <script type="text/javascript">googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350912979829-0'); });</script>
                            </div>
                            <div id='div-gpt-ad-1457810657334-2' style='height:250px; width:300px;'>
                                <script type='text/javascript'>
                                    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1457810657334-2'); });
                                </script>
                            </div>
                        </div>
                    <?php endif; ?>
                    <a href="<?php echo $this->customUrl(array('nomConcours' => $concPrec->getLibelleConcours(), 'idConcours' => $concPrec->getNomConcours()), 'concoursstep1'); ?>">
                        <div class="block white rounded">
                            <?php $filename = file_exists(ROOT_PATH.PUBLIC_DIR.'/images/concours/'.$concPrec->getNomConcours().'.jpg') ? '/images/concours/'.$concPrec->getNomConcours().'.jpg' : '/img/temp/scev6-tempconcours-small.jpg'; ?>
                            <figure class="row">
                                <img src="<?php echo $filename ?>" alt="concours bande-dessinée, gagner bande-dessinée, <?php echo str_replace(array('\'', '"', '`'), '', $concPrec->getLibelleConcours()) ?>" class="illus" />
                                <?php if ($concPrec->getResultats() != '') : ?>
                                    <span class="results">Résultats disponibles</span>
                                <?php endif; ?>
                            </figure>
                            <h2><?php echo $concPrec->getLibelleConcours() ?></h2>
                            <p><?php echo strip_tags($concPrec->getEntete() ) ?></p>
                        </div>
                    </a>
                <?php endforeach; ?>
               </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>