
        
<!-- CONTENU -->

<header class="header-mauve">
	<div class="search">
		<form action="<?php echo $this->customUrl( array('tag' => '') , 'recherche') ?>" method="get">
			<input type="text" name="tag" value='<?php echo isset($this->requeteUser)? $this->requeteUser : '' ?>' placeholder="Rechercher">
			
			<div class="menu">
                            <a href="javascript:void(0);">Tout le site</a>
                            <ul>
                                <li>Titre ou série</li>
                                <li>Les auteurs</li>
                                <li>Les éditeurs</li>
                                <li>ISBN</li>
                                <li>Les rédacteurs</li>
                            </ul>
			</div>
			<input type="hidden" name="filter" value="">
			<input type="submit" name="" value="Rechercher">
		</form>
		
		<p>ou</p>
			
		<form action="<?php echo $this->customUrl( array('tag' => '') , 'recherche') ?>" method="get">
                    <div class="menu">
                        <a href="">Rechercher par thème</a>
                        <ul>
                        <?php foreach($this->genres as  $genre): ?>
                        <li><?php echo  $genre   ?></li>
                        <?php endforeach; ?>   
                        </ul>
                    </div>
                    <input type="hidden" name="tag" value="">
                    <input type="submit" name="" value="Rechercher">
		</form>
	</div><!-- search -->
</header>

<div class="leftRecherche">
	<header>
            <p class="left">
            Résultats <?php echo $this -> pageRequested > 1 
                                 ? $this->resultsPerPage * ($this -> pageRequested-1) 
                                 : 1 ?> 
                à <?php echo ($this->countResults < $this->resultsPerPage) 
                             ?  $this->countResults 
                             :  ((($this->resultsPerPage * $this -> pageRequested) < $this->countResults) 
                                                                                   ? $this->resultsPerPage * $this -> pageRequested
                                                                                   : $this->countResults ) ;

                ?> sur <?php echo $this->countResults ?></p>
            <p class="right">Afficher 
                    <select name="" onchange="self.location.href = '<?php echo $this->currentUrl ?>&results='+this.value">
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 10 )echo "SELECTED" ?> value="10">10</option>
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 20 )echo "SELECTED" ?> value="20">20</option>
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 30 )echo "SELECTED" ?> value="30">30</option>
                        <option <?php if(isset($_GET['results']) && $_GET['results'] == 50 )echo "SELECTED" ?> value="50">50</option>
                    </select> 
            résultats par page</p>
	</header>
	<?php if (count($this->paginator)): ?>
	
        

<?php foreach ($this->paginator as $key => $hit): ?>
  <?php
    $coverUri = $this->customUrl(array('isbn'   => $hit->isbn ,'format' => 'small'), 'couverture') ;
            ?>
            
        <div class="item">
           
		<a href="<?php echo $this->customUrl( array('titleSerie' => $hit->titreSerie , 
                                                            'titleAlbum' => $hit->titreAlbum, 
                                                            'idAlbum'    => $hit->idAlbum ) , 
                                                            'album'); ?>" class="masque"></a>
	
            <?php echo $this->displayImage($coverUri, 'cover-' . $hit->isbn, 'cover'  ) ?>    
      
                <div class="search-content">
                    <hgroup>
                        <h1><?php echo $hit->titreSerie ?></h1>
                        <h2><?php echo $hit->titreAlbum ?></h2>
                    </hgroup>

                    <p>
                    <?php  echo $hit->auteurs ?>

                    <?php if($hit->editeur != ''):?>
                        <br />Editions <?php echo $hit->editeur  ?>
                    <?php endif ?>
                    </p>
                    <?php 

                    if($hit->genres != ''): ?>
                        <p><?php echo $hit->genres ?></p>
                    <?php endif; ?>

                 </div>
                <div class="clear"></div>
	</div>
        
  
<?php endforeach; ?>

<?php endif; ?>
       
<div class="separateur"></div>
 
<?php


echo $this->paginationControl( $this->paginator,
                               'Sliding',
                               'paginationControl.phtml' ); ?>
	
</div>

<div class="rightRecherche">
    	<?php 
	   echo $this->userAccountWidget('user_dashboard');
	   echo $this->lastConcoursBloc($this) ; 
	?>
        
	<!-- Pub 300x250 -->
	<div class="pub">
            <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Recherche300pub -->
            <div id='div-gpt-ad-1350913318651-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913318651-0'); });
                </script>
            </div>
            <!-- Recherche300interne -->
            <div id='div-gpt-ad-1350913404071-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913404071-0'); });
                </script>
            </div>
	</div><!-- pub -->
	
    
    
		<?php 
		echo $this->lastInterviewBloc($this);
		echo $this->lastGalleryBloc($this);
		echo $this->lastExpoBloc($this);
		echo $this->lastGalleryBloc($this, 'preview');
		echo $this->registerNewsletter($this);
		?>
		<div class="clear"></div>
	
	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" 
             data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 
</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>

    
