<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <?php print isset($this->headOpenTag) && !empty($this->headOpenTag) ? $this->headOpenTag : '<head>'; ?>
        <meta charset="utf-8">
        <?php print ($this->headTitle() != '<title></title>') ? $this->headTitle() : '<title>Sceneario.com - Toute la bande dessinée sur Sceneario.com</title>'; ?>
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
        <?php if ($this->headMeta() != '') : ?>
        <?php   print $this->headMeta(); ?>
        <?php else : ?>
        <?php   $description = "Site consacr&eacute; &agrave; la BD : critiques, r&eacute;sum&eacute;s, nouveaut&eacute;s, interviews, concours..."; ?>
        <?php   $keywords    = "BD, CRITIQUE, RESUME, INTERVIEW, NOUVEAUTE, SERIE, BDS, CRITIQUES, BANDES DESSINEES, BANDE DESSINEE, SERIES "; ?>
        <meta name="description" content="<?php echo isset($this->albumDescription) ? $this->albumDescription  :$description ?>">
        <meta name="keywords"  content="<?php echo isset($this->albumKeywordsRef) ? $this->albumKeywordsRef : $keywords ?>">
        <meta name="Copyright" content="Sceneario.com">
        <meta name="publisher" content="Sceneario.com">
        <meta name="Expires" content="Never">
        <meta name="Revisit-after" content="7 days">
        <meta name="category" content="bandes dessinées">
        <meta name="robots" content="index, follow">
        <meta name="verify-v1" content="N9yzsROn12aL6salWXxgqz9U9aeSzxhFu6F5tzj6CEs=" />
        <meta name="verify-v1" content="gaTlT4pYBU3oc5bHuB1iio1MQ0nKVDThl1XDZcaCbkI=" />
        <meta name="verify-v1" content="VF0vdLsuK++ubFin2MVOAykZjtpfZu3OmDF79DGWFHI=" />
        <meta name="google-site-verification" content="7M4o6nF28RlM0UiRZFplC7X0zWmr_rs_k3dLep5urGg" />
        <meta name="google-site-verification" content="hjRrgEsA5m2vA4R5ApfOTEB5UcejlbUAo56wumw7kNg" />
        <meta name="y_key" content="cbf954200f12df6f" />
        <meta property="og:title" content="Sceneario.com"/>
        <meta property="og:type" content="website"/>
        <meta property="og:image" content="http://<?php echo $_SERVER['HTTP_HOST'] ?>/img/temp/v6-img6.jpg"/>
        <meta property="og:url" content="http://<?php echo $_SERVER['HTTP_HOST'] ?>"/>
        <meta property="og:site_name" content="Sceneario.com"/>
        <meta property="og:description" content="<?php echo $description ?>"/>
        <?php endif; ?>
        <link rel="canonical" href="<?php echo $this->currentUrl() ?>" />
        <!--[if lt IE 9]> <link rel="stylesheet" href="css/ie.css"> <![endif]-->
        <!--[if IE 7]> <link rel="stylesheet" href="css/ie7.css"> <![endif]-->
        <script src="http://<?php echo $_SERVER['HTTP_HOST'] ?>/js/googledbc.js"></script>
    </head>
    <body>
        <?php if ($this->applyFilter == true) : ?>
            <style>
                #adultFilter { position: fixed; width: 100%; height: 100%; background: #DDD; z-index: 10000; text-align: center; vertical-align: vertical-align; opacity:0.9; }
                #adultFilter div{ float: none; outline:0px solid red; margin :  0 auto; margin-top:180px; background: #666; padding: 20px; -moz-box-shadow: 0 0 5px #888; -webkit-box-shadow: 0 0 5px#888; box-shadow: 0 0 5px #888; color:white; -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px; border:2px solid white; }
                #adultFilter div .heading-1{ line-height: 30px; font-size: 25px; font-weight: bold; margin: 0.67em 0; }
                #adultFilter div p.text { width:300px; margin :  0 auto; text-align: justify; padding-bottom: 20px; }
                .filterlink { outline: 0px solid red; float:left; width: 50px; font-weight: bolder; font-size:20px; }
                .filterlink:hover { color:white; }
                .out { float:right; }
            </style>
            <div id="adultFilter">
                <div class="col-xs-12 col-md-3">
                    <p class="heading-1">ATTENTION : CONTENU RESERVE <br />A UN PUBLIC AVERTI</p>
                    <p class="text">Les images et textes à caractère érotique, pornographique ou violent contenus dans cette page peuvent choquer certaines sensibilités.
                    <br />En affichant cette page, vous déclarez prendre vos responsabilités vis-a-vis de ce contenu.</p>
                    <p class="text">
                       <a class="filterlink in" href="javascript:void(0);" onclick="document.getElementById('adultFilter').style.display = 'none'">Afficher</a>
                       <a class="filterlink out" href="<?php echo $this->referer ?>">Sortir</a>
                    </p>
                </div>
            </div>
        <?php endif;?>
        <?php if (!$this->isMobile) : ?>
        <div id="fb-root"></div>
        <?php if(APPLICATION_ENV == 'testing' || APPLICATION_ENV == 'development'): ?>
            <!--
            <script>
                window.fbAsyncInit = function() {
                    FB.init({
                      appId      : '277280558967434',
                      channelUrl : '//dev.sceneario.com/tool/channel',
                      status     : true,
                      cookie     : true,
                      oauth      : true,
                      xfbml      : true
                    });
                };
                (function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;js.async = true;
                    js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=277280558967434";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>
            -->
        <?php else: ?>
            <script>
                window.fbAsyncInit = function() {
                    FB.init({
                      appId      : '277280558967434',
                      channelUrl : '//www.sceneario.com/tool/channel',
                      status     : true,
                      cookie     : true,
                      oauth      : true,
                      xfbml      : true
                    });
                  };
                (function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;js.async = true;
                    js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1&appId=277280558967434";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>
        <?php endif; ?>
        <?php endif; ?>
        <header>
            <?php if (!$this->isMobile) : ?>
            <div id="pub">
                <div class="container">
                    <?php $chartotrash = array('"','\'','(',')'); ?>
                    <?php if (count($this->motcles) > 0) : ?>
                    <?php   $pubgenre = array(); ?>
                    <?php   foreach ($this->motcles as $key => $motscles) : ?>
                    <?php     $pubgenre[] = $motscles->libelle; ?>
                    <?php   endforeach; ?>
                    <?php endif; ?>
                    <?php $pubauteurs = array(); ?>
                    <?php if (count($this->dessinateurs) > 0) : ?>
                    <?php   foreach ($this->dessinateurs as $dessinateurs) : ?>
                    <?php     $pubauteurs[] = $dessinateurs->prenomAuteur.' '.$dessinateurs->nomAuteur; ?>
                    <?php   endforeach; ?>
                    <?php endif;?>
                    <?php if (count($this->scenaristes) > 0) : ?>
                    <?php   foreach ($this->scenaristes as $scenariste) : ?>
                    <?php     $pubauteurs[] = $scenariste->prenomAuteur.' '.$scenariste->nomAuteur; ?>
                    <?php   endforeach; ?>
                    <?php endif; ?>
                    <?php if (count($this->coloristes) > 0) : ?>
                    <?php   foreach ($this->coloristes as $coloriste): ?>
                    <?php     $pubauteurs[] = $coloriste->prenomAuteur.' '.$coloriste->nomAuteur; ?>
                    <?php   endforeach ?>
                    <?php endif; ?>
                    <div id='div-gpt-ad-1390927229792-0'>
                    <script type='text/javascript'>
                    googletag.cmd.push(function() {
                        <?php if (isset($this->albumInfos)) : ?>
                        googletag.pubads().setTargeting("titre", "<?php echo str_replace($chartotrash, '', $this->albumInfos->getTitre()); ?>");
                        <?php endif; ?>
                        <?php if (isset($this->serieInfos)) : ?>
                        googletag.pubads().setTargeting("serie", "<?php echo str_replace($chartotrash, '', $this->albumInfos->getCollection()); ?>");
                        <?php endif; ?>
                        <?php if (!empty($pubauteurs)) : ?>
                        googletag.pubads().setTargeting("auteurs", "<?php echo str_replace($chartotrash, '', implode(',', $pubauteurs)); ?>");
                        <?php endif; ?>
                        <?php if (!empty($pubgenre)) : ?>
                        googletag.pubads().setTargeting("genre", "<?php echo str_replace($chartotrash, '', implode(',', $pubgenre)); ?>");
                        <?php endif; ?>
                        googletag.display('div-gpt-ad-1390927229792-0');
                    });
                    </script>
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div id="main-head" class="navbar navbar-default">
                <div id="head-container">
                    <div id="head" class="container">
                        <div class="row">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainMenu">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a id="logo" class="navbar-brand col-xs-9 col-md-12" href="<?php echo BASE_URL ?>">
                                    <img class="img-responsive" src="<?php echo BASE_URL ?>img/logo_sceneario.png" alt="Sceneario.com - Toute la BD sur internet" />
                                </a>
                            </div>
                            <?php if (!$this->isMobile) : ?>
                            <div class="search pull-right">
                                <form method='get' action="<?php echo $this->customUrl( array() , 'recherche') ?>">
                                    <input type="text" name="tag" value='<?php echo isset($this->requeteUser) && $this->userFilter != 'genres' ?$this->requeteUser:'' ?>' placeholder="Rechercher">
                                </form>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div id="nav-container">
                    <nav id="mainnav" class="navbar navbar-default">
                        <div class="container">
                            <?php if (!$this->isMobile) : ?>
                                <?php echo $this->userAccountWidget('user_connect_shortcut'); ?>
                            <?php endif; ?>
                            <div id="mainMenu" class="row collapse navbar-collapse">
                                <ul class="mainMenu">
                                    <li><a href="/">Accueil</a></li>
                                    <li><a href="/blog">Actualités</a></li>
                                    <li><a href="/bande-dessinee">Bédéthèque</a><ul>
                                        <li><a href="/bande-dessinee/series">Les séries</a></li>
                                        <li><a href="/bande-dessinee/albums">Les albums</a></li>
                                        <li><a href="/bande-dessinee/auteurs">Les auteurs</a></li>
                                        <li><a href="/bande-dessinee/nouveautes">Nouveautés</a></li>
                                        <li><a href="/bande-dessinee/prochaines-parutions">A paraitre</a></li>
                                        <li><a href="/bande-dessinee/coupsdecoeur">Coup de coeur</a></li>
                                        <li><a href="/bande-dessinee/recommandes">Recommandés</a></li>
                                    </ul></li>
                                    <li><a href="#">Toute la bd</a><ul>
                                        <li><a href="/interview">Interviews</a></li>
                                        <li><a href="/expositions-salons">Expositions, salons</a></li>
                                        <li><a href="/galerie">Galeries</a></li>
                                        <li><a href="/preview">Previews</a></li>
                                    </ul></li>
                                    <li><a href="/concours">Concours</a></li>
                                    <?php if ($this->isMobile) : ?>
                                    <li class="visible-xs">
                                        <form action="<?php echo $this->customUrl( array('tag' => '') , 'recherche') ?>" class="navbar-form navbar-left" role="search">
                                            <div class="form-group col-xs-8">
                                                <input type="text" class="form-control" placeholder="un album, une série, ..." name="tag" value="<?php echo isset($this->requeteUser)? $this->requeteUser : '' ?>" />
                                            </div>
                                            <div class="col-xs-4">
                                                <button type="submit" class="btn btn-default">Rechercher</button>
                                            </div>
                                        </form>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
        <div id="content-container">
            <?php if (!$this->isMobile) : ?>
                <?php echo $this->partial('partials/habillagesPub.phtml', array('habillageHome' => $this->habillageHome)); ?>
            <?php endif; ?>
	    <div class="container">
            <div id="content" class="row">
                <?php print $this->layout()->content ?>
            </div>
	    </div>
        </div>
        <footer id="mainfooter">
            <?php if (!$this->isMobile) : ?>
            <div id="header">
                <div class="container">
                    <div class="row">
                        <?php echo $this->partial('partials/socialContacts.phtml', array('class' => 'col-md-4 pull-right', 'color' => 'green')); ?>
                        <div class="search">
                            <form method='get' action="<?php echo $this->customUrl( array() , 'recherche') ?>">
                                <input type="text" name="tag" value='<?php echo isset($this->requeteUser)?$this->requeteUser:'' ?>' placeholder="Rechercher">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <?php else : ?>
                <div class="container"><div class="row"><?php echo $this->partial('partials/socialContacts.phtml', array('color' => 'pink')); ?></div></div>
            <?php endif; ?>
            <div id="sitemap">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-md-4">
                            <h3>Plan du site</h3>
                            <p class="text-justify">
                                <a href="http://www.sceneario.com">Sceneario.com</a> est un site généraliste traitant de Bande Dessinée, spécialisé dans la critique de BD, de Comics et de Mangas. Avec plus de 20 000 fiches BDs résumant et analysant les parutions internationales, 550 interviews, 450 préviews, 270 comptes rendus d’expositions&nbsp;/&nbsp;salons, 180 galeries de croquis, des concours, Sceneario.com est un site de référence et un incontournable du monde de la Bande Dessinée.
                            </p>
                        </div>
                        <ul class="mainMenu col-md-7 col-md-offset-1">
                            <li class="col-md-2 col-md-offset-2 col-xs-4"><h4><a href="/accueil.html">Sceneario</a></h4>
                                <ul>
                                    <li><a href="/equipe">Équipe</a></li>
                                    <li><a href="/newsletter">Newsletter</a></li>
                                    <li><a href="/mentions-legales">Mentions légales</a></li>
                                    <li><a href="http://regie.sceneario.com" target="_blank">Régie Pub</a></li>
                                    <li><a target="_blank" href="http://www.facebook.com/Sceneario.com">Facebook</a></li>
                                    <li><a target="_blank" href="https://twitter.com/sceneario">Twitter</a></li>
                                    <li><a target="_blank" href="/blog/feed/rss">RSS</a></li>
                                    <li><a href="<?php echo $this->url(array(), 'contact', true); ?>">Contact</a></li>
                                </ul>
                            </li>
                            <li class="col-md-2 col-xs-4"><h4><a href="/bande-dessinee.html">Bédéthèque</a></h4>
                                <ul>
                                  <li><a href="/bande-dessinee/nouveautes.html">Nouveautés</a></li>
                                  <li><a href="/bande-dessinee/prochaines-parutions.html">A paraitre</a></li>
                                  <li><a href="/bande-dessinee/coupsdecoeur.html">Coup de coeur</a></li>
                                  <li><a href="/bande-dessinee/recommandes.html">Recommandés</a></li>
                                </ul>
                            </li>
                            <li class="col-md-2 col-xs-4"><h4><a href="/sceneario-passe-la-6eme.html">Toute la bd</a></h4>
                                <ul>
                                  <li><a href="/interview">Interviews</a></li>
                                  <li><a href="/expositions-salons">Expositions, salons</a></li>
                                  <li><a href="/galerie">Galeries</a></li>
                                  <li><a href="/preview">Previews</a></li>
                                </ul>
                            </li>
                            <li class="col-md-2 col-xs-4"><h4><a href="/blog">Actualités</a></h4>
                                <ul><li><a href="/blog">Blog</a></li></ul>
                            </li>
                            <li class="col-md-2 col-xs-4"><h4><a href="/concours">Concours</a></h4>
                                <ul>
                                    <li><a href="/concours">Tous les concours</a></li>
                                    <?php $c = Core_Model_Mapper_Tblconcoursent::getCurrentConcours(); ?>
                                    <?php if (!empty($c)) : ?>
                                    <li><a href="<?php echo $this->customUrl( array( 'nomConcours' => $c[0]->getLibelleConcours(), 'idConcours'  => $c[0]->getNomConcours()) , 'concoursstep1'); ?>">À gagner en ce moment</a></li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <p><a href="http://www.sceneario.com">Sceneario.com</a> V6.0 © Association Sceneario.com loi 1901 - Tous droits réservés</p>
                        <a href="http://www.sceneario.com"><img src="/img/footer_logo.png" alt="critiques BD, comics, mangas"></a>
                    </div>
                </div>
            </div>
        </footer>
        <link rel="stylesheet" href="<?php echo BASE_URL ?>min/?g=css">
        <?php echo implode('', $this->block_css); ?>
        <script src="<?php echo BASE_URL ?>min/?g=js-vendor"></script>
        <script src="<?php echo BASE_URL ?>min/?g=js"></script>
        <?php echo implode('', $this->block_js); ?>
        <script type="text/javascript">
            sas_pageid='66595/511465';    // Page : Sceneario/sceneario-all
            sas_formatid=29314;                // Format : Interstitiel 0x0
            sas_target='';                                     // Ciblage
            SmartAdServer(sas_pageid,sas_formatid,sas_target);
        </script>
        <noscript>
            <a href="http://www3.smartadserver.com/call/pubjumpi/66595/511465/29314/S/<?php echo time(); ?>/?" target="_blank">
            <img src="http://www3.smartadserver.com/call/pubi/66595/511465/29314/S/<?php echo time(); ?>/?" border="0" alt="" /></a>
        </noscript>
        <?php if (APPLICATION_ENV != 'development' || APPLICATION_ENV != 'testing'): ?>
            <script>
                var _gaq=[['_setAccount','UA-964631-1'],['_trackPageview']];
                (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
                g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
                s.parentNode.insertBefore(g,s)}(document,'script'));
            </script>
        <?php endif; echo PHP_EOL ; ?>
    </body>
</html>
