<?php
    $requeteUser = urlencode($_GET['cleanedTag']);

    $resultsPerPage = "";
    if (isset($_GET['results'])) {
        $resultsPerPage = '&results=' . urlencode($_GET['results']);
    }

    if (isset($_GET['filter'])) {
        $resultsPerPage = '&filter=' . urlencode($_GET['filter']);
    }
?>
<?php if ($this->pageCount) : ?>
<div class="pagination" style="width:100%;">
    <?php if (isset($this->previous)): ?>
        <?php $previous = '/recherche?tag='.$requeteUser.'&page='. $this->previous . $resultsPerPage; ?>
        <a class="prev" href="<?php echo $previous ; ?>">Page précédente</a>
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <?php $current  = '/recherche?tag='.$requeteUser.'&page='. $page . $resultsPerPage; ?>
            <a class="page" href="<?php echo $current  ?>"><?php echo $page; ?></a>
        <?php else: ?>
            <?php $current  = '/recherche?tag='.$requeteUser.'&page='. $page . $resultsPerPage; ?>
            <a href="<?php echo $current ?>" class="page active"><?php echo $page; ?></a>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
        <?php $next = '/recherche?tag='.$requeteUser.'&page='. $this->next . $resultsPerPage; ?>
        <a class="next" href="<?php echo $next ;?>">Page suivante</a>
    <?php endif; ?>
</div>
<?php endif; ?>