<div class="interview col-xs-12 col-md-8">
    <div class="interview-title">
        <h2><a href="<?php echo $this->customUrl(array(), 'listinterview'); ?>">Interview</a></h2> -
        <h1><a href="<?php echo $this->currentUrl(); ?>">
            <?php foreach ($this->auteurs as $k => $auteur) : ?>
                <?php echo $auteur->getPrenomAuteur().' '.$auteur->getNomAuteur().($k+1 < count($this->auteurs) ? ' - ' : ''); ?>
            <?php endforeach; ?>
        </a></h1>
    </div>
    <section class="block white col-xs-12 rounded">
        <figure class="row">
            <img class="illus" src="<?php echo $this->imageInterview; ?>" alt="interview bande-dessinée, interview auteurs bande-dessinée, <?php echo $this->titreInterview; ?>" />
        </figure>
        <hgroup>
            <h1><?php echo $this->titreInterview; ?></h1>
            <h2><?php echo $this->soustitreInterview; ?></h2>
        </hgroup>
        <div id="texte"><?php echo $this->textInterview; ?></div>
        <?php echo $this->partial('partials/social_links.phtml', $this); ?>
    </section>
</div>
<?php echo $this->partial('partials/sidebar.phtml'); ?>