   
<!-- CONTENU -->

<div class="leftActu">
	<h1><a href="<?php echo $this -> customUrl(array(),'listinterview') ?>">Interview</a><?php echo $this -> nomAuteur ?></h1>
	
	<section class="interview-wrapper">
		<figure  style="background-image:url(<?php echo $this -> imageInterview ?>);background-repeat:no-repeat;">
			<img src="/img/block620_white_masque.png" alt="" class="masque">
		</figure>
		
		<hgroup>
			<h1><?php echo $this -> titreInterview ; ?></h1>
			<h2><?php echo $this -> soustitreInterview ; ?></h2>
		</hgroup>
		   
		<div id="texte"><?php echo $this -> textInterview ; ?></div>
                
		<!-- Bloc de liens réseaux sociaux -->
		<div class="social-links">
                <div class="fb-like" data-href="<?php echo $this->currentUrl() ?>" data-send="true" data-layout="button_count" data-width="100" data-show-faces="false" data-action="recommend" data-font="arial"></div>
			
			<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120"></div>

			<script type="text/javascript">
			  window.___gcfg = {lang: 'fr'};

			  (function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
		</div>
	</section>
</div>

<div class="rightActu">
  <?php 
     echo $this->userAccountWidget('user_dashboard');
     echo $this->lastConcoursBloc($this);
  ?>
 
	<!-- Pub 300x250 -->
	<div class="pub">
            <?php echo $this->partial('partials/pubs300large.phtml'); ?>
            <!-- Interview300 -->
            <div id='div-gpt-ad-1350913175803-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913175803-0'); });
                </script>
            </div>
            <!-- Interview300interne -->
            <div id='div-gpt-ad-1350913216188-0'>
                <script type='text/javascript'>
                googletag.cmd.push(function() { googletag.display('div-gpt-ad-1350913216188-0'); });
                </script>
            </div>
	</div><!-- pub -->
	
	 	<?php 
		echo $this->lastInterviewBloc($this);  
		echo $this->lastGalleryBloc($this);
		echo $this->lastExpoBloc($this);
		echo $this->lastGalleryBloc($this, 'preview');
		echo $this->registerNewsletter($this);
		?>
	<div class="clear"></div>

	<!-- Facebook like box -->
	<div class="fb-like-box" data-href="http://www.facebook.com/Sceneario.com" data-width="300" data-show-faces="true" data-border-color="#fff" data-stream="false" data-header="false"></div><!-- Facebook like box --> 

</div>

<!-- Reinitialisation des float -->
<div class="clear"></div>
