    
        
<!-- CONTENU -->

<header class="header-mauve" id="bedetheque">
    <p>Aujourd'hui sur Sceneario, découvrez <span><?php echo $this->countInterview ?></span> interviews inédites et passionantes de vos auteurs préférés</p>
</header>

<div class="clear" style="height:50px;"></div>

 
    
<?php
#$interviewLen = count($this->blocInterview);

 $a = $b = $c = array();
 $c[] = '<!-- Pub 300x250 -->
<div class="pub">
    <!-- Home300x250 -->
    <div id="div-gpt-ad-1350912979829-0"  style="width:300px; height:250px;">
        <script type="text/javascript">
        googletag.cmd.push(function() { googletag.display(\'div-gpt-ad-1350912979829-0\'); });
        </script>
    </div>
</div><!-- pub --> ';
foreach( $this->paginator as $key => $bloc): 

    $keyModulo = $key % 3 ;
    switch($keyModulo){
        case 0 :
            $a[] = $bloc ;
            break;
        case 1 :
            $b[] = $bloc ;
            break;
        case 2 :
            $c[] = $bloc ;
            break;
    }
 endforeach;
 
 
 $blocDatas =  array($a,$b,$c);
 
 #echo '<pre>';
 #print_r ($blocDatas);
 #exit('</pre>');
 
 foreach($blocDatas as $key => $blocs):
    $noMarginRight = '';
    if($key > 1):
        $noMarginRight = 'style="margin-right:0;"' ;
    endif ;
    ?>
     
    <div class="bloc2col rounded"  <?php echo $noMarginRight ?>>
    <?php 
     foreach($blocs as $key => $bloc):
        #echo $key ;
        echo $bloc;
    endforeach;
    ?>
    </div>
        <?php
endforeach;

?><div class="clear"></div>

<div class="clear"></div>
       
<div class="separateur"></div>
 
<?php


echo $this->paginationControl( $this->paginator,
                               'Sliding',
                               'paginationControl-interview-type.phtml' ); ?>
	<?php /*


<div class="bloc2col rounded">
 
</div><!-- bloc2col -->

<div class="bloc2col rounded">
	 
</div><!-- bloc2col -->
    */ ?>
<!-- Reinitialisation des float -->
<div class="clear"></div>
